// Canonical Contextual Readings and Romaji for all 347 Kanji in the Curriculum
// Maps each Kanji to its primary lesson-context reading, standard Hepburn romaji, and core meaning.

export const KANJI_CONTEXTUAL_READINGS = {
  "一": { reading: "いち", romaji: "ichi", meaning: "one", lesson: 6 },
  "二": { reading: "に", romaji: "ni", meaning: "two", lesson: 6 },
  "三": { reading: "さん", romaji: "san", meaning: "three", lesson: 6 },
  "日": { reading: "ひ / にち", romaji: "hi / nichi", meaning: "day, sun", lesson: 6 },
  "月": { reading: "つき / げつ", romaji: "tsuki / getsu", meaning: "month, moon", lesson: 6 },
  "木": { reading: "き / もく", romaji: "ki / moku", meaning: "tree, wood", lesson: 6 },
  "山": { reading: "やま", romaji: "yama", meaning: "mountain", lesson: 6 },
  "川": { reading: "かわ", romaji: "kawa", meaning: "river", lesson: 6 },
  "人": { reading: "ひと / じん", romaji: "hito / jin", meaning: "person", lesson: 6 },
  "口": { reading: "くち", romaji: "kuchi", meaning: "mouth", lesson: 6 },
  "願": { reading: "ねが(う)", romaji: "nega(u)", meaning: "request, wish", lesson: 7 },
  "初": { reading: "はじ(め)", romaji: "haji(me)", meaning: "first, beginning", lesson: 7 },
  "先": { reading: "せん", romaji: "sen", meaning: "before, previous, teacher", lesson: 7 },
  "生": { reading: "せい", romaji: "sei", meaning: "life, birth, student", lesson: 7 },
  "失": { reading: "しつ", romaji: "shitsu", meaning: "lose, fault", lesson: 7 },
  "礼": { reading: "れい", romaji: "rei", meaning: "courtesy, gratitude", lesson: 7 },
  "私": { reading: "わたし", romaji: "watashi", meaning: "I, me, private", lesson: 8 },
  "彼": { reading: "かれ", romaji: "kare", meaning: "he, that", lesson: 8 },
  "女": { reading: "じょ / おんな", romaji: "jo / onna", meaning: "woman, female", lesson: 8 },
  "学": { reading: "がく", romaji: "gaku", meaning: "study, learn", lesson: 8 },
  "会": { reading: "かい", romaji: "kai", meaning: "meeting, company", lesson: 8 },
  "社": { reading: "しゃ", romaji: "sha", meaning: "company, society", lesson: 8 },
  "員": { reading: "いん", romaji: "in", meaning: "member, employee", lesson: 8 },
  "本": { reading: "ほん", romaji: "hon", meaning: "book, origin, real", lesson: 8 },
  "友": { reading: "とも", romaji: "tomo", meaning: "friend", lesson: 8 },
  "達": { reading: "だち / たつ", romaji: "dachi / tatsu", meaning: "attain, plural marker", lesson: 8 },
  "誰": { reading: "だれ", romaji: "dare", meaning: "who", lesson: 8 },
  "何": { reading: "なに / なん", romaji: "nani / nan", meaning: "what", lesson: 8 },
  "名": { reading: "な / めい", romaji: "na / mei", meaning: "name, reputation", lesson: 8 },
  "前": { reading: "まえ / ぜん", romaji: "mae / zen", meaning: "front, before", lesson: 8 },
  "辞": { reading: "じ", romaji: "ji", meaning: "word, phrase", lesson: 9 },
  "書": { reading: "しょ / か(く)", romaji: "sho / ka(ku)", meaning: "book, write", lesson: 9 },
  "傘": { reading: "かさ", romaji: "kasa", meaning: "umbrella", lesson: 9 },
  "鍵": { reading: "かぎ", romaji: "kagi", meaning: "key", lesson: 9 },
  "車": { reading: "くるま / しゃ", romaji: "kuruma / sha", meaning: "car, vehicle", lesson: 9 },
  "時": { reading: "じ / とき", romaji: "ji / toki", meaning: "time, hour, clock", lesson: 9 },
  "計": { reading: "けい", romaji: "kei", meaning: "measure, plan", lesson: 9 },
  "四": { reading: "よん", romaji: "yon", meaning: "four", lesson: 10 },
  "五": { reading: "ご", romaji: "go", meaning: "five", lesson: 10 },
  "六": { reading: "ろく", romaji: "roku", meaning: "six", lesson: 10 },
  "七": { reading: "なな", romaji: "nana", meaning: "seven", lesson: 10 },
  "八": { reading: "はち", romaji: "hachi", meaning: "eight", lesson: 10 },
  "九": { reading: "きゅう", romaji: "kyuu", meaning: "nine", lesson: 10 },
  "十": { reading: "じゅう", romaji: "juu", meaning: "ten", lesson: 10 },
  "百": { reading: "ひゃく", romaji: "hyaku", meaning: "hundred", lesson: 10 },
  "歳": { reading: "さい", romaji: "sai", meaning: "year-end", lesson: 10 },
  "財": { reading: "さい", romaji: "sai", meaning: "property", lesson: 10 },
  "布": { reading: "ふ", romaji: "fu", meaning: "linen", lesson: 10 },
  "家": { reading: "いえ / うち", romaji: "ie / uchi", meaning: "house, home", lesson: 10 },
  "族": { reading: "ぞく", romaji: "zoku", meaning: "family, tribe", lesson: 10 },
  "父": { reading: "ちち / とう", romaji: "chichi / tou", meaning: "father", lesson: 10 },
  "母": { reading: "はは / かあ", romaji: "haha / kaa", meaning: "mother", lesson: 10 },
  "食": { reading: "た(べる) / しょく", romaji: "ta(beru) / shoku", meaning: "eat, food", lesson: 11 },
  "飲": { reading: "の(む) / いん", romaji: "no(mu) / in", meaning: "drink", lesson: 11 },
  "読": { reading: "よ(む)", romaji: "yo(mu)", meaning: "read", lesson: 11 },
  "聞": { reading: "ぶん / き(く)", romaji: "bun / ki(ku)", meaning: "hear, listen", lesson: 11 },
  "見": { reading: "み(る)", romaji: "mi(ru)", meaning: "see, look, watch", lesson: 11 },
  "行": { reading: "い(く) / こう", romaji: "i(ku) / kou", meaning: "go, conduct", lesson: 11 },
  "来": { reading: "く(る) / らい", romaji: "ku(ru) / rai", meaning: "come, next", lesson: 11 },
  "帰": { reading: "かえ(る)", romaji: "kae(ru)", meaning: "return, go home", lesson: 11 },
  "飯": { reading: "はん / めし", romaji: "han / meshi", meaning: "meal, cooked rice", lesson: 11 },
  "水": { reading: "みず / すい", romaji: "mizu / sui", meaning: "water", lesson: 11 },
  "茶": { reading: "ちゃ", romaji: "cha", meaning: "tea", lesson: 11 },
  "校": { reading: "こう", romaji: "kou", meaning: "school", lesson: 11 },
  "図": { reading: "ず / と", romaji: "zu / to", meaning: "diagram, map", lesson: 11 },
  "館": { reading: "かん", romaji: "kan", meaning: "building, hall", lesson: 11 },
  "駅": { reading: "えき", romaji: "eki", meaning: "train station", lesson: 11 },
  "起": { reading: "お(きる)", romaji: "o(kiru)", meaning: "wake up, get up", lesson: 12 },
  "寝": { reading: "ね(る)", romaji: "ne(ru)", meaning: "sleep, lie down", lesson: 12 },
  "勉": { reading: "べん", romaji: "ben", meaning: "exertion, study", lesson: 12 },
  "強": { reading: "きょう / つよ(い)", romaji: "kyou / tsuyo(i)", meaning: "strong", lesson: 12 },
  "今": { reading: "いま / こん", romaji: "ima / kon", meaning: "now, present", lesson: 12 },
  "明": { reading: "めい / あした", romaji: "mei / ashita", meaning: "bright, tomorrow", lesson: 12 },
  "昨": { reading: "さく / きのう", romaji: "saku / kinou", meaning: "previous, yesterday", lesson: 12 },
  "毎": { reading: "まい", romaji: "mai", meaning: "every", lesson: 12 },
  "朝": { reading: "あさ / ちょう", romaji: "asa / chou", meaning: "morning", lesson: 12 },
  "昼": { reading: "ひる / ちゅう", romaji: "hiru / chuu", meaning: "noon, daytime", lesson: 12 },
  "夜": { reading: "よる / や", romaji: "yoru / ya", meaning: "night", lesson: 12 },
  "分": { reading: "ふん / ぶん", romaji: "fun / bun", meaning: "minute, part, understand", lesson: 12 },
  "午": { reading: "ご", romaji: "go", meaning: "noon", lesson: 12 },
  "後": { reading: "ご", romaji: "go", meaning: "behind", lesson: 12 },
  "男": { reading: "おとこ", romaji: "otoko", meaning: "male", lesson: 13 },
  "子": { reading: "こ / し", romaji: "ko / shi", meaning: "child", lesson: 13 },
  "供": { reading: "ども / きょう", romaji: "domo / kyou", meaning: "companion, offer", lesson: 13 },
  "犬": { reading: "いぬ", romaji: "inu", meaning: "dog", lesson: 13 },
  "猫": { reading: "ねこ", romaji: "neko", meaning: "cat", lesson: 13 },
  "机": { reading: "つくえ", romaji: "tsukue", meaning: "desk", lesson: 13 },
  "椅": { reading: "い", romaji: "i", meaning: "chair", lesson: 13 },
  "部": { reading: "へ / ぶ", romaji: "he / bu", meaning: "room, section, part", lesson: 13 },
  "屋": { reading: "や / おく", romaji: "ya / oku", meaning: "room, shop, roof", lesson: 13 },
  "上": { reading: "うえ / じょう", romaji: "ue / jou", meaning: "above, top", lesson: 13 },
  "下": { reading: "した / か", romaji: "shita / ka", meaning: "below, under", lesson: 13 },
  "中": { reading: "なか / ちゅう", romaji: "naka / chuu", meaning: "inside, middle", lesson: 13 },
  "話": { reading: "はな(す) / わ", romaji: "hana(su) / wa", meaning: "speak, talk, story", lesson: 14 },
  "待": { reading: "ま", romaji: "ma", meaning: "wait", lesson: 14 },
  "買": { reading: "か(う)", romaji: "ka(u)", meaning: "buy", lesson: 14 },
  "電": { reading: "でん", romaji: "den", meaning: "electricity", lesson: 14 },
  "緒": { reading: "しょ", romaji: "sho", meaning: "thong", lesson: 14 },
  "約": { reading: "やく", romaji: "yaku", meaning: "promise", lesson: 14 },
  "束": { reading: "そく", romaji: "soku", meaning: "bundle", lesson: 14 },
  "手": { reading: "て", romaji: "te", meaning: "hand", lesson: 14 },
  "紙": { reading: "がみ / かみ", romaji: "gami / kami", meaning: "paper", lesson: 14 },
  "映": { reading: "えい", romaji: "ei", meaning: "reflect", lesson: 14 },
  "画": { reading: "が", romaji: "ga", meaning: "brush-stroke", lesson: 14 },
  "店": { reading: "みせ / てん", romaji: "mise / ten", meaning: "shop, store", lesson: 14 },
  "週": { reading: "しゅう", romaji: "shuu", meaning: "week", lesson: 14 },
  "末": { reading: "まつ", romaji: "matsu", meaning: "end", lesson: 14 },
  "物": { reading: "もの / ぶつ", romaji: "mono / butsu", meaning: "thing, object", lesson: 14 },
  "公": { reading: "こう", romaji: "kou", meaning: "public", lesson: 14 },
  "園": { reading: "えん", romaji: "en", meaning: "park", lesson: 14 },
  "大": { reading: "おお / だい", romaji: "oo / dai", meaning: "big, large", lesson: 15 },
  "小": { reading: "ちい", romaji: "chii", meaning: "little", lesson: 15 },
  "高": { reading: "たか", romaji: "taka", meaning: "tall", lesson: 15 },
  "安": { reading: "やす", romaji: "yasu", meaning: "relax", lesson: 15 },
  "新": { reading: "しん / あたら(しい)", romaji: "shin / atara(shii)", meaning: "new", lesson: 15 },
  "古": { reading: "ふる", romaji: "furu", meaning: "old", lesson: 15 },
  "良": { reading: "い", romaji: "i", meaning: "good", lesson: 15 },
  "悪": { reading: "わる", romaji: "waru", meaning: "bad", lesson: 15 },
  "暑": { reading: "あつ", romaji: "atsu", meaning: "sultry", lesson: 15 },
  "寒": { reading: "さむ", romaji: "samu", meaning: "cold", lesson: 15 },
  "熱": { reading: "あつ", romaji: "atsu", meaning: "heat", lesson: 15 },
  "冷": { reading: "つめ", romaji: "tsume", meaning: "cool", lesson: 15 },
  "美": { reading: "おいしい", romaji: "oishii", meaning: "beauty", lesson: 15 },
  "味": { reading: "あじ", romaji: "aji", meaning: "flavor", lesson: 15 },
  "楽": { reading: "たの", romaji: "tano", meaning: "music", lesson: 15 },
  "面": { reading: "おもしろい", romaji: "omoshiroi", meaning: "mask", lesson: 15 },
  "白": { reading: "しろ", romaji: "shiro", meaning: "white", lesson: 15 },
  "忙": { reading: "いそが", romaji: "isoga", meaning: "busy", lesson: 15 },
  "静": { reading: "しず", romaji: "shizu", meaning: "quiet", lesson: 16 },
  "賑": { reading: "にぎ", romaji: "nigi", meaning: "bustling", lesson: 16 },
  "有": { reading: "ゆう", romaji: "yuu", meaning: "possess", lesson: 16 },
  "親": { reading: "しん", romaji: "shin", meaning: "parent", lesson: 16 },
  "切": { reading: "き(る) / せつ", romaji: "ki(ru) / setsu", meaning: "cut", lesson: 16 },
  "元": { reading: "げん", romaji: "gen", meaning: "beginning", lesson: 16 },
  "気": { reading: "き", romaji: "ki", meaning: "spirit", lesson: 16 },
  "暇": { reading: "ひま", romaji: "hima", meaning: "spare time", lesson: 16 },
  "便": { reading: "べん", romaji: "ben", meaning: "convenience", lesson: 16 },
  "利": { reading: "り", romaji: "ri", meaning: "profit", lesson: 16 },
  "不": { reading: "ふ", romaji: "fu", meaning: "negative", lesson: 16 },
  "綺": { reading: "き", romaji: "ki", meaning: "figured cloth", lesson: 16 },
  "麗": { reading: "れい", romaji: "rei", meaning: "lovely", lesson: 16 },
  "好": { reading: "す", romaji: "su", meaning: "fond", lesson: 16 },
  "嫌": { reading: "きら", romaji: "kira", meaning: "dislike", lesson: 16 },
  "丈": { reading: "じょう", romaji: "jou", meaning: "sturdy", lesson: 16 },
  "夫": { reading: "ぶ", romaji: "bu", meaning: "husband", lesson: 16 },
  "簡": { reading: "かん", romaji: "kan", meaning: "simplicity", lesson: 16 },
  "単": { reading: "たん", romaji: "tan", meaning: "simple", lesson: 16 },
  "変": { reading: "へん", romaji: "hen", meaning: "unusual", lesson: 16 },
  "番": { reading: "ばん", romaji: "ban", meaning: "turn", lesson: 17 },
  "少": { reading: "すこ", romaji: "suko", meaning: "few", lesson: 17 },
  "全": { reading: "ぜん", romaji: "zen", meaning: "whole", lesson: 17 },
  "然": { reading: "ぜん", romaji: "zen", meaning: "sort of thing", lesson: 17 },
  "世": { reading: "せ", romaji: "se", meaning: "generation", lesson: 17 },
  "界": { reading: "かい", romaji: "kai", meaning: "world", lesson: 17 },
  "季": { reading: "き", romaji: "ki", meaning: "seasons", lesson: 17 },
  "節": { reading: "せつ", romaji: "setsu", meaning: "node", lesson: 17 },
  "春": { reading: "はる", romaji: "haru", meaning: "springtime", lesson: 17 },
  "夏": { reading: "なつ", romaji: "natsu", meaning: "summer", lesson: 17 },
  "秋": { reading: "あき", romaji: "aki", meaning: "autumn", lesson: 17 },
  "冬": { reading: "ふゆ", romaji: "fuyu", meaning: "winter", lesson: 17 },
  "入": { reading: "い", romaji: "i", meaning: "enter", lesson: 18 },
  "洗": { reading: "あら", romaji: "ara", meaning: "wash", lesson: 19 },
  "立": { reading: "た", romaji: "ta", meaning: "stand up", lesson: 19 },
  "座": { reading: "すわ", romaji: "suwa", meaning: "squat", lesson: 19 },
  "取": { reading: "と", romaji: "to", meaning: "take", lesson: 19 },
  "呼": { reading: "よ", romaji: "yo", meaning: "call", lesson: 19 },
  "遊": { reading: "あそ", romaji: "aso", meaning: "play", lesson: 19 },
  "歩": { reading: "ある", romaji: "aru", meaning: "walk", lesson: 19 },
  "泳": { reading: "およ", romaji: "oyo", meaning: "swim", lesson: 19 },
  "急": { reading: "いそ", romaji: "iso", meaning: "hurry", lesson: 19 },
  "出": { reading: "だ", romaji: "da", meaning: "exit", lesson: 19 },
  "借": { reading: "か", romaji: "ka", meaning: "borrow", lesson: 19 },
  "貸": { reading: "か", romaji: "ka", meaning: "lend", lesson: 19 },
  "開": { reading: "あ", romaji: "a", meaning: "open", lesson: 19 },
  "閉": { reading: "し", romaji: "shi", meaning: "closed", lesson: 19 },
  "住": { reading: "す", romaji: "su", meaning: "dwell", lesson: 20 },
  "知": { reading: "し", romaji: "shi", meaning: "know", lesson: 20 },
  "持": { reading: "も", romaji: "mo", meaning: "hold", lesson: 20 },
  "働": { reading: "はたら(く)", romaji: "hatara(ku)", meaning: "work", lesson: 20 },
  "覚": { reading: "おぼ", romaji: "obo", meaning: "memorize", lesson: 20 },
  "忘": { reading: "わす", romaji: "wasu", meaning: "forget", lesson: 20 },
  "着": { reading: "き", romaji: "ki", meaning: "don", lesson: 20 },
  "履": { reading: "は", romaji: "ha", meaning: "perform", lesson: 20 },
  "結": { reading: "けっこん", romaji: "kekkon", meaning: "tie", lesson: 20 },
  "婚": { reading: "こん", romaji: "kon", meaning: "marriage", lesson: 20 },
  "独": { reading: "どく", romaji: "doku", meaning: "single", lesson: 20 },
  "身": { reading: "しん", romaji: "shin", meaning: "somebody", lesson: 20 },
  "所": { reading: "しょ", romaji: "sho", meaning: "place", lesson: 20 },
  "号": { reading: "ごう", romaji: "gou", meaning: "nickname", lesson: 20 },
  "写": { reading: "しゃ / うつ(す)", romaji: "sha / utsu(su)", meaning: "copy, photograph", lesson: 21 },
  "真": { reading: "しん / ま", romaji: "shin / ma", meaning: "true, reality", lesson: 21 },
  "撮": { reading: "と", romaji: "to", meaning: "snapshot", lesson: 21 },
  "吸": { reading: "す", romaji: "su", meaning: "suck", lesson: 21 },
  "病": { reading: "びょう", romaji: "byou", meaning: "ill", lesson: 21 },
  "院": { reading: "いん", romaji: "in", meaning: "institution", lesson: 21 },
  "術": { reading: "じゅつ", romaji: "jutsu", meaning: "art", lesson: 21 },
  "声": { reading: "こえ", romaji: "koe", meaning: "voice", lesson: 21 },
  "窓": { reading: "まど", romaji: "mado", meaning: "window", lesson: 21 },
  "席": { reading: "せき", romaji: "seki", meaning: "seat", lesson: 21 },
  "荷": { reading: "に / か", romaji: "ni / ka", meaning: "luggage, cargo", lesson: 21 },
  "当": { reading: "とう", romaji: "tou", meaning: "hit", lesson: 22 },
  "嘘": { reading: "うそ", romaji: "uso", meaning: "lie", lesson: 22 },
  "多": { reading: "た", romaji: "ta", meaning: "many", lesson: 22 },
  "晩": { reading: "ばん", romaji: "ban", meaning: "evening, night", lesson: 22 },
  "宿": { reading: "しゅく", romaji: "shuku", meaning: "inn", lesson: 22 },
  "題": { reading: "だい", romaji: "dai", meaning: "topic", lesson: 22 },
  "授": { reading: "じゅ", romaji: "ju", meaning: "impart", lesson: 22 },
  "業": { reading: "ぎょう", romaji: "gyou", meaning: "business", lesson: 22 },
  "休": { reading: "やす(む)", romaji: "yasu(mu)", meaning: "rest, take time off", lesson: 22 },
  "思": { reading: "おも", romaji: "omo", meaning: "think", lesson: 23 },
  "言": { reading: "い", romaji: "i", meaning: "say", lesson: 23 },
  "考": { reading: "かんが", romaji: "kanga", meaning: "consider", lesson: 23 },
  "意": { reading: "い", romaji: "i", meaning: "idea", lesson: 23 },
  "質": { reading: "しつ", romaji: "shitsu", meaning: "substance", lesson: 23 },
  "問": { reading: "もん", romaji: "mon", meaning: "question", lesson: 23 },
  "答": { reading: "こた", romaji: "kota", meaning: "solution", lesson: 23 },
  "雑": { reading: "ざつ", romaji: "zatsu", meaning: "miscellaneous", lesson: 23 },
  "誌": { reading: "し", romaji: "shi", meaning: "magazine, record", lesson: 23 },
  "葉": { reading: "は", romaji: "ha", meaning: "leaf", lesson: 23 },
  "文": { reading: "ぶん", romaji: "bun", meaning: "sentence", lesson: 23 },
  "化": { reading: "か", romaji: "ka", meaning: "change", lesson: 23 },
  "将": { reading: "しょう", romaji: "shou", meaning: "leader", lesson: 23 },
  "天": { reading: "てん", romaji: "ten", meaning: "heavens", lesson: 23 },
  "予": { reading: "よ", romaji: "yo", meaning: "beforehand", lesson: 23 },
  "報": { reading: "ほう", romaji: "hou", meaning: "report", lesson: 23 },
  "方": { reading: "かた", romaji: "kata", meaning: "direction", lesson: 24 },
  "料": { reading: "りょう", romaji: "ryou", meaning: "fee", lesson: 24 },
  "理": { reading: "り", romaji: "ri", meaning: "logic", lesson: 24 },
  "弁": { reading: "べん", romaji: "ben", meaning: "valve", lesson: 24 },
  "菓": { reading: "か", romaji: "ka", meaning: "candy", lesson: 24 },
  "服": { reading: "ふく", romaji: "fuku", meaning: "clothing", lesson: 24 },
  "靴": { reading: "くつ", romaji: "kutsu", meaning: "shoes", lesson: 24 },
  "帽": { reading: "ぼう", romaji: "bou", meaning: "cap", lesson: 24 },
  "眼": { reading: "め", romaji: "me", meaning: "eyeball", lesson: 24 },
  "鏡": { reading: "かがみ", romaji: "kagami", meaning: "mirror", lesson: 24 },
  "場": { reading: "ば", romaji: "ba", meaning: "location", lesson: 24 },
  "町": { reading: "まち", romaji: "machi", meaning: "town", lesson: 24 },
  "道": { reading: "みち", romaji: "michi", meaning: "road-way", lesson: 24 },
  "作": { reading: "つく", romaji: "tsuku", meaning: "make", lesson: 24 },
  "脱": { reading: "ぬ", romaji: "nu", meaning: "undress", lesson: 24 },
  "落": { reading: "お", romaji: "o", meaning: "fall", lesson: 24 },
  "旅": { reading: "りょ", romaji: "ryo", meaning: "trip", lesson: 25 },
  "観": { reading: "かん", romaji: "kan", meaning: "outlook", lesson: 25 },
  "光": { reading: "こう", romaji: "kou", meaning: "ray", lesson: 25 },
  "土": { reading: "つち", romaji: "tsuchi", meaning: "soil", lesson: 25 },
  "産": { reading: "うむ", romaji: "umu", meaning: "products", lesson: 25 },
  "符": { reading: "ぷ / ふ", romaji: "pu / fu", meaning: "token, tally, ticket", lesson: 25 },
  "飛": { reading: "ひ", romaji: "hi", meaning: "fly", lesson: 25 },
  "機": { reading: "き", romaji: "ki", meaning: "loom", lesson: 25 },
  "空": { reading: "くう", romaji: "kuu", meaning: "empty", lesson: 25 },
  "港": { reading: "こう", romaji: "kou", meaning: "harbor", lesson: 25 },
  "趣": { reading: "しゅ", romaji: "shu", meaning: "purport", lesson: 25 },
  "音": { reading: "おん", romaji: "on", meaning: "sound", lesson: 25 },
  "歌": { reading: "うた", romaji: "uta", meaning: "song", lesson: 25 },
  "欲": { reading: "ほ", romaji: "ho", meaning: "longing", lesson: 25 },
  "金": { reading: "かね", romaji: "kane", meaning: "gold", lesson: 25 },
  "自": { reading: "じ", romaji: "ji", meaning: "oneself", lesson: 25 },
  "転": { reading: "てん", romaji: "ten", meaning: "revolve", lesson: 25 },
  "富": { reading: "ふ", romaji: "fu", meaning: "wealth", lesson: 26 },
  "士": { reading: "さむらい", romaji: "samurai", meaning: "gentleman", lesson: 26 },
  "登": { reading: "のぼ", romaji: "nobo", meaning: "ascend", lesson: 26 },
  "温": { reading: "おん", romaji: "on", meaning: "warm", lesson: 26 },
  "泉": { reading: "せん", romaji: "sen", meaning: "spring", lesson: 26 },
  "泊": { reading: "と", romaji: "to", meaning: "overnight stay", lesson: 26 },
  "乗": { reading: "の", romaji: "no", meaning: "ride", lesson: 26 },
  "度": { reading: "ど", romaji: "do", meaning: "degrees", lesson: 26 },
  "掃": { reading: "そう", romaji: "sou", meaning: "sweep", lesson: 26 },
  "除": { reading: "のぞく", romaji: "nozoku", meaning: "exclude", lesson: 26 },
  "濯": { reading: "たく", romaji: "taku", meaning: "laundry", lesson: 26 },
  "散": { reading: "さん", romaji: "san", meaning: "scatter", lesson: 26 },
  "運": { reading: "うん", romaji: "un", meaning: "carry", lesson: 26 },
  "動": { reading: "どう", romaji: "dou", meaning: "move", lesson: 26 },
  "神": { reading: "じん", romaji: "jin", meaning: "gods", lesson: 26 },
  "寺": { reading: "てら", romaji: "tera", meaning: "Buddhist temple", lesson: 26 },
  "祭": { reading: "まつ", romaji: "matsu", meaning: "ritual", lesson: 26 },
  "経": { reading: "けい", romaji: "kei", meaning: "sutra", lesson: 26 },
  "験": { reading: "けん", romaji: "ken", meaning: "verification", lesson: 26 },
  "弾": { reading: "ひ", romaji: "hi", meaning: "bullet", lesson: 27 },
  "外": { reading: "そと / がい", romaji: "soto / gai", meaning: "outside, foreign", lesson: 27 },
  "国": { reading: "くに / こく", romaji: "kuni / koku", meaning: "country, nation", lesson: 27 },
  "語": { reading: "ご", romaji: "go", meaning: "language, word", lesson: 27 },
  "英": { reading: "えい", romaji: "ei", meaning: "England", lesson: 27 },
  "通": { reading: "つう", romaji: "tsuu", meaning: "traffic", lesson: 27 },
  "漢": { reading: "かん", romaji: "kan", meaning: "Sino-", lesson: 27 },
  "字": { reading: "じ", romaji: "ji", meaning: "character", lesson: 27 },
  "発": { reading: "はつ", romaji: "hatsu", meaning: "departure", lesson: 27 },
  "得": { reading: "とく", romaji: "toku", meaning: "gain", lesson: 27 },
  "苦": { reading: "にが", romaji: "niga", meaning: "suffering", lesson: 27 },
  "直": { reading: "なお", romaji: "nao", meaning: "straightaway", lesson: 27 },
  "練": { reading: "れん", romaji: "ren", meaning: "practice", lesson: 27 },
  "習": { reading: "しゅう", romaji: "shuu", meaning: "learn", lesson: 27 },
  "薬": { reading: "くすり", romaji: "kusuri", meaning: "medicine", lesson: 28 },
  "風": { reading: "かぜ", romaji: "kaze", meaning: "wind", lesson: 28 },
  "邪": { reading: "よこしま", romaji: "yokoshima", meaning: "wicked", lesson: 28 },
  "医": { reading: "い", romaji: "i", meaning: "doctor", lesson: 28 },
  "者": { reading: "しゃ", romaji: "sha", meaning: "someone", lesson: 28 },
  "保": { reading: "ほ", romaji: "ho", meaning: "protect", lesson: 28 },
  "険": { reading: "けん", romaji: "ken", meaning: "precipitous", lesson: 28 },
  "証": { reading: "しょう", romaji: "shou", meaning: "evidence", lesson: 28 },
  "規": { reading: "き", romaji: "ki", meaning: "standard", lesson: 28 },
  "則": { reading: "そく", romaji: "soku", meaning: "rule", lesson: 28 },
  "法": { reading: "ほう", romaji: "hou", meaning: "method", lesson: 28 },
  "律": { reading: "りつ", romaji: "ritsu", meaning: "rhythm", lesson: 28 },
  "守": { reading: "まも", romaji: "mamo", meaning: "guard", lesson: 28 },
  "払": { reading: "はら", romaji: "hara", meaning: "pay", lesson: 28 },
  "渡": { reading: "わた", romaji: "wata", meaning: "transit", lesson: 28 },
  "提": { reading: "てい", romaji: "tei", meaning: "propose", lesson: 28 },
  "期": { reading: "き", romaji: "ki", meaning: "period", lesson: 28 },
  "限": { reading: "げん", romaji: "gen", meaning: "limit", lesson: 28 },
  "無": { reading: "む", romaji: "mu", meaning: "nothingness", lesson: 28 },
  "体": { reading: "からだ", romaji: "karada", meaning: "body", lesson: 29 },
  "頭": { reading: "あたま", romaji: "atama", meaning: "head", lesson: 29 },
  "腹": { reading: "はら", romaji: "hara", meaning: "abdomen", lesson: 29 },
  "痛": { reading: "いた", romaji: "ita", meaning: "pain", lesson: 29 },
  "心": { reading: "しん", romaji: "shin", meaning: "heart", lesson: 29 },
  "配": { reading: "くばる", romaji: "kubaru", meaning: "distribute", lesson: 29 },
  "健": { reading: "けん", romaji: "ken", meaning: "healthy", lesson: 29 },
  "康": { reading: "こう", romaji: "kou", meaning: "ease", lesson: 29 },
  "野": { reading: "や", romaji: "ya", meaning: "plains", lesson: 29 },
  "菜": { reading: "さい", romaji: "sai", meaning: "vegetable", lesson: 29 },
  "早": { reading: "はや", romaji: "haya", meaning: "early", lesson: 29 },
  "睡": { reading: "すい", romaji: "sui", meaning: "drowsy", lesson: 29 },
  "眠": { reading: "みん", romaji: "min", meaning: "sleep", lesson: 29 },
  "甘": { reading: "あま", romaji: "ama", meaning: "sweet", lesson: 29 },
  "辛": { reading: "から", romaji: "kara", meaning: "spicy", lesson: 29 },
  "塩": { reading: "しお", romaji: "shio", meaning: "salt", lesson: 29 },
  "砂": { reading: "さ", romaji: "sa", meaning: "sand", lesson: 29 },
  "糖": { reading: "とう", romaji: "tou", meaning: "sugar", lesson: 29 },
  "都": { reading: "つ", romaji: "tsu", meaning: "metropolis", lesson: 30 },
  "合": { reading: "ごう", romaji: "gou", meaning: "fit", lesson: 30 },
  "用": { reading: "よう", romaji: "you", meaning: "utilize", lesson: 30 },
  "事": { reading: "じ", romaji: "ji", meaning: "matter", lesson: 30 },
  "定": { reading: "てい", romaji: "tei", meaning: "determine", lesson: 30 },
  "遅": { reading: "おく", romaji: "oku", meaning: "slow", lesson: 30 },
  "間": { reading: "あいだ / かん", romaji: "aida / kan", meaning: "interval, space, between", lesson: 30 },
  "故": { reading: "こ", romaji: "ko", meaning: "happenstance", lesson: 30 },
  "障": { reading: "しょう", romaji: "shou", meaning: "obstacle", lesson: 30 },
  "台": { reading: "たい", romaji: "tai", meaning: "pedestal", lesson: 30 },
  "地": { reading: "じ", romaji: "ji", meaning: "ground", lesson: 30 },
  "震": { reading: "しん", romaji: "shin", meaning: "quake", lesson: 30 },
  "火": { reading: "か", romaji: "ka", meaning: "fire", lesson: 30 },
  "由": { reading: "ゆ", romaji: "yu", meaning: "wherefore", lesson: 30 },
  "確": { reading: "たし", romaji: "tashi", meaning: "assurance", lesson: 30 },
  "残": { reading: "ざん", romaji: "zan", meaning: "remainder", lesson: 30 },
  "念": { reading: "ねん", romaji: "nen", meaning: "wish", lesson: 30 },
};

export function getKanjiLessonReading(char) {
  return KANJI_CONTEXTUAL_READINGS[char] || null;
}
