#!/usr/bin/env node
require('dotenv').config({ path: '.env.local' });
const connectDB = require('../src/lib/mongodb.js').default || require('../src/lib/mongodb.js');
const { ObjectId } = require('mongodb');

const TARGET_DECK_ID = '6a9902aa37d59c56011b69f7';

const cards = [
  {
    type: 'grammar',
    category: 'Basic Grammar',
    jlpt: 'N5',
    tags: ['N5', 'grammar', 'cha-ikenai'],
    kanji: '',
    reading: '',
    romaji: '',
    meaning: 'ちゃいけない・じゃいけない — must not; may not',
    partOfSpeech: '',
    example: 'ここで写真を撮っちゃいけません。',
    exampleReading: 'ここで しゃしんを とっちゃ いけません。',
    exampleMeaning: 'You must not take pictures here.',
    grammar: 'ちゃいけない / じゃいけない',
    formation: 'て-form + は → ちゃ; では → じゃ + いけない',
    usage: 'Used to say that an action is prohibited or must not be done. Common in spoken Japanese.',
    grammarExamples: [
      { japanese: 'ここで写真を撮っちゃいけません。', reading: 'ここで しゃしんを とっちゃ いけません。', english: 'You must not take pictures here.' },
      { japanese: '学校に遅れちゃいけない。', reading: 'がっこうに おくれちゃ いけない。', english: 'You must not be late for school.' },
    ],
    negative: '',
    past: '',
    pastNegative: '',
    commonMistake: 'ちゃいけない is the spoken contraction of てはいけない. じゃいけない comes from ではいけない.',
    formalAlternative: 'てはいけない / ではいけない',
    interval: 0,
    repetitions: 0,
    easeFactor: 2.5,
    dueDate: Date.now(),
  },

  {
    type: 'grammar',
    category: 'Basic Grammar',
    jlpt: 'N5',
    tags: ['N5', 'grammar', 'desu'],
    kanji: '',
    reading: '',
    romaji: '',
    meaning: 'だ / です — to be; am; is; are',
    partOfSpeech: '',
    example: '私は学生です。',
    exampleReading: 'わたしは がくせいです。',
    exampleMeaning: 'I am a student.',
    grammar: 'だ / です',
    formation: 'Noun + だ / です; な-adjective + だ / です',
    usage: 'Used to state or identify something. です is the polite form, while だ is the plain form.',
    grammarExamples: [
      { japanese: '私は学生です。', reading: 'わたしは がくせいです。', english: 'I am a student.' },
      { japanese: 'これは本です。', reading: 'これは ほんです。', english: 'This is a book.' },
    ],
    negative: 'ではありません / じゃない',
    past: 'でした / だった',
    pastNegative: 'ではありませんでした / じゃなかった',
    commonMistake: 'だ is not normally used after い-adjectives. For example, おいしいです is correct, not おいしいだ.',
    formalAlternative: 'です',
    interval: 0,
    repetitions: 0,
    easeFactor: 2.5,
    dueDate: Date.now(),
  },

  {
    type: 'grammar',
    category: 'Quantity',
    jlpt: 'N5',
    tags: ['N5', 'grammar', 'dake'],
    kanji: 'だけ',
    reading: 'だけ',
    romaji: 'dake',
    meaning: 'だけ — only; just; as much as',
    partOfSpeech: '',
    example: '水だけ飲みました。',
    exampleReading: 'みずだけ のみました。',
    exampleMeaning: 'I drank only water.',
    grammar: 'だけ',
    formation: 'Noun + だけ; Verb + だけ; Adjective + だけ',
    usage: 'Indicates limitation: only, just, or an amount limited to something.',
    grammarExamples: [
      { japanese: '水だけ飲みました。', reading: 'みずだけ のみました。', english: 'I drank only water.' },
      { japanese: 'これだけください。', reading: 'これだけ ください。', english: 'Please give me only this.' },
    ],
    negative: '',
    past: '',
    pastNegative: '',
    commonMistake: 'だけ normally comes directly after the word or phrase being limited.',
    formalAlternative: '',
    interval: 0,
    repetitions: 0,
    easeFactor: 2.5,
    dueDate: Date.now(),
  },

  {
    type: 'grammar',
    category: 'Probability',
    jlpt: 'N5',
    tags: ['N5', 'grammar', 'darou'],
    kanji: 'だろう',
    reading: 'だろう',
    romaji: 'darou',
    meaning: 'だろう — probably; I think; it seems; right?',
    partOfSpeech: '',
    example: '明日は雨だろう。',
    exampleReading: 'あしたは あめだろう。',
    exampleMeaning: 'It will probably rain tomorrow.',
    grammar: 'だろう',
    formation: 'Plain form + だろう',
    usage: 'Expresses probability, an assumption, or the speaker\'s opinion. It can also seek agreement.',
    grammarExamples: [
      { japanese: '明日は雨だろう。', reading: 'あしたは あめだろう。', english: 'It will probably rain tomorrow.' },
      { japanese: '彼は来るだろう。', reading: 'かれは くるだろう。', english: 'He will probably come.' },
    ],
    negative: '',
    past: '',
    pastNegative: '',
    commonMistake: 'だろう is less polite than でしょう. Use でしょう in polite conversation.',
    formalAlternative: 'でしょう',
    interval: 0,
    repetitions: 0,
    easeFactor: 2.5,
    dueDate: Date.now(),
  },

  {
    type: 'grammar',
    category: 'Particles',
    jlpt: 'N5',
    tags: ['N5', 'grammar', 'de'],
    kanji: 'で',
    reading: 'で',
    romaji: 'de',
    meaning: 'で — in; at; on; by; with; via',
    partOfSpeech: '',
    example: '学校で日本語を勉強します。',
    exampleReading: 'がっこうで にほんごを べんきょうします。',
    exampleMeaning: 'I study Japanese at school.',
    grammar: 'で',
    formation: 'Place + で + action',
    usage: 'Marks the place where an action occurs, the means or method used, or sometimes the material or cause.',
    grammarExamples: [
      { japanese: '学校で日本語を勉強します。', reading: 'がっこうで にほんごを べんきょうします。', english: 'I study Japanese at school.' },
      { japanese: 'バスで行きます。', reading: 'バスで いきます。', english: 'I go by bus.' },
    ],
    negative: '',
    past: '',
    pastNegative: '',
    commonMistake: 'Do not use で for the existence of something. Use に with あります/います.',
    formalAlternative: '',
    interval: 0,
    repetitions: 0,
    easeFactor: 2.5,
    dueDate: Date.now(),
  },

  {
    type: 'grammar',
    category: 'Conjunction',
    jlpt: 'N5',
    tags: ['N5', 'grammar', 'demo'],
    kanji: 'でも',
    reading: 'でも',
    romaji: 'demo',
    meaning: 'でも — but; however; though',
    partOfSpeech: '',
    example: '行きたいです。でも、時間がありません。',
    exampleReading: 'いきたいです。でも、じかんが ありません。',
    exampleMeaning: "I want to go. But I don't have time.",
    grammar: 'でも',
    formation: 'Sentence 1 + でも + Sentence 2',
    usage: "Connects contrasting ideas and means 'but' or 'however'.",
    grammarExamples: [
      { japanese: 'この店は小さいです。でも、きれいです。', reading: 'このみせは ちいさいです。でも、きれいです。', english: 'This shop is small. However, it is clean.' },
      { japanese: '食べたい。でも、お金がありません。', reading: 'たべたい。でも、おかねが ありません。', english: "I want to eat it. But I don't have money." },
    ],
    negative: '',
    past: '',
    pastNegative: '',
    commonMistake: 'でも at the beginning of a sentence means \'but/however\'. The particle でも has other meanings.',
    formalAlternative: 'しかし',
    interval: 0,
    repetitions: 0,
    easeFactor: 2.5,
    dueDate: Date.now(),
  },

  {
    type: 'grammar',
    category: 'Basic Grammar',
    jlpt: 'N5',
    tags: ['N5', 'grammar', 'deshou'],
    kanji: 'でしょう',
    reading: 'でしょう',
    romaji: 'deshou',
    meaning: 'でしょう — probably; I think; it seems; right?',
    partOfSpeech: '',
    example: '明日は暑いでしょう。',
    exampleReading: 'あしたは あついでしょう。',
    exampleMeaning: 'It will probably be hot tomorrow.',
    grammar: 'でしょう',
    formation: 'Plain form + でしょう',
    usage: 'Expresses probability, uncertainty, or an expectation. It can also be used to ask for agreement.',
    grammarExamples: [
      { japanese: '明日は暑いでしょう。', reading: 'あしたは あついでしょう。', english: 'It will probably be hot tomorrow.' },
      { japanese: 'これは難しいでしょう。', reading: 'これは むずかしいでしょう。', english: 'This will probably be difficult.' },
    ],
    negative: '',
    past: '',
    pastNegative: '',
    commonMistake: 'でしょう is the polite equivalent commonly used instead of plain だろう.',
    formalAlternative: '',
    interval: 0,
    repetitions: 0,
    easeFactor: 2.5,
    dueDate: Date.now(),
  },

  {
    type: 'grammar',
    category: 'Question Words',
    jlpt: 'N5',
    tags: ['N5', 'grammar', 'donna'],
    kanji: 'どんな',
    reading: 'どんな',
    romaji: 'donna',
    meaning: 'どんな — what kind of; what sort of',
    partOfSpeech: '',
    example: 'どんな音楽が好きですか。',
    exampleReading: 'どんな おんがくが すきですか。',
    exampleMeaning: 'What kind of music do you like?',
    grammar: 'どんな',
    formation: 'どんな + Noun',
    usage: 'Asks about the type, kind, or characteristics of a noun.',
    grammarExamples: [
      { japanese: 'どんな音楽が好きですか。', reading: 'どんな おんがくが すきですか。', english: 'What kind of music do you like?' },
      { japanese: 'どんな人ですか。', reading: 'どんな ひとですか。', english: 'What kind of person is he/she?' },
    ],
    negative: '',
    past: '',
    pastNegative: '',
    commonMistake: 'どんな must normally be followed by a noun.',
    formalAlternative: '',
    interval: 0,
    repetitions: 0,
    easeFactor: 2.5,
    dueDate: Date.now(),
  },

  {
    type: 'grammar',
    category: 'Question Words',
    jlpt: 'N5',
    tags: ['N5', 'grammar', 'doushite'],
    kanji: 'どうして',
    reading: 'どうして',
    romaji: 'doushite',
    meaning: 'どうして — why; for what reason',
    partOfSpeech: '',
    example: 'どうして日本語を勉強しますか。',
    exampleReading: 'どうして にほんごを べんきょうしますか。',
    exampleMeaning: 'Why do you study Japanese?',
    grammar: 'どうして',
    formation: 'どうして + Sentence',
    usage: 'Used to ask the reason or cause of something.',
    grammarExamples: [
      { japanese: 'どうして日本語を勉強しますか。', reading: 'どうして にほんごを べんきょうしますか。', english: 'Why do you study Japanese?' },
      { japanese: 'どうして遅れましたか。', reading: 'どうして おくれましたか。', english: 'Why were you late?' },
    ],
    negative: '',
    past: '',
    pastNegative: '',
    commonMistake: "どうして asks 'why', while どうやって asks 'how'.",
    formalAlternative: 'なぜ',
    interval: 0,
    repetitions: 0,
    easeFactor: 2.5,
    dueDate: Date.now(),
  },

  {
    type: 'grammar',
    category: 'Question Words',
    jlpt: 'N5',
    tags: ['N5', 'grammar', 'douyatte'],
    kanji: 'どうやって',
    reading: 'どうやって',
    romaji: 'douyatte',
    meaning: 'どうやって — how; in what way; by what means',
    partOfSpeech: '',
    example: 'どうやって学校へ行きますか。',
    exampleReading: 'どうやって がっこうへ いきますか。',
    exampleMeaning: 'How do you go to school?',
    grammar: 'どうやって',
    formation: 'どうやって + Verb',
    usage: 'Asks about the method, means, or way of doing something.',
    grammarExamples: [
      { japanese: 'どうやって学校へ行きますか。', reading: 'どうやって がっこうへ いきますか。', english: 'How do you go to school?' },
      { japanese: 'どうやって作りますか。', reading: 'どうやって つくりますか。', english: 'How do you make it?' },
    ],
    negative: '',
    past: '',
    pastNegative: '',
    commonMistake: 'どうやって asks about method, not reason. Use どうして for "why".',
    formalAlternative: '',
    interval: 0,
    repetitions: 0,
    easeFactor: 2.5,
    dueDate: Date.now(),
  },

  {
    type: 'grammar',
    category: 'Particles',
    jlpt: 'N5',
    tags: ['N5', 'grammar', 'ga'],
    kanji: 'が',
    reading: 'が',
    romaji: 'ga',
    meaning: 'が — subject marker; but; however',
    partOfSpeech: '',
    example: '猫がいます。',
    exampleReading: 'ねこが います。',
    exampleMeaning: 'There is a cat.',
    grammar: 'が',
    formation: 'Noun + が + Verb/Adjective',
    usage: 'Marks the grammatical subject. It can also connect clauses with a contrastive meaning such as "but".',
    grammarExamples: [
      { japanese: '猫がいます。', reading: 'ねこが います。', english: 'There is a cat.' },
      { japanese: '日本語が好きです。', reading: 'にほんごが すきです。', english: 'I like Japanese.' },
    ],
    negative: '',
    past: '',
    pastNegative: '',
    commonMistake: 'が marks the subject, while を normally marks the direct object.',
    formalAlternative: '',
    interval: 0,
    repetitions: 0,
    easeFactor: 2.5,
    dueDate: Date.now(),
  },

  {
    type: 'grammar',
    category: 'Existence',
    jlpt: 'N5',
    tags: ['N5', 'grammar', 'ga-arimasu'],
    kanji: 'があります',
    reading: 'があります',
    romaji: 'ga arimasu',
    meaning: 'があります — there is; there are; to have (non-living)',
    partOfSpeech: '',
    example: '机の上に本があります。',
    exampleReading: 'つくえの うえに ほんが あります。',
    exampleMeaning: 'There is a book on the desk.',
    grammar: 'があります',
    formation: 'Place + に + Noun + があります',
    usage: 'Indicates the existence or presence of non-living things. It can also express possession.',
    grammarExamples: [
      { japanese: '机の上に本があります。', reading: 'つくえの うえに ほんが あります。', english: 'There is a book on the desk.' },
      { japanese: '車があります。', reading: 'くるまが あります。', english: 'I have a car.' },
    ],
    negative: 'ありません',
    past: 'ありました',
    pastNegative: 'ありませんでした',
    commonMistake: 'Use います for people and animals; use あります for things and plants.',
    formalAlternative: '',
    interval: 0,
    repetitions: 0,
    easeFactor: 2.5,
    dueDate: Date.now(),
  },

  {
    type: 'grammar',
    category: 'Desire',
    jlpt: 'N5',
    tags: ['N5', 'grammar', 'hoshii'],
    kanji: 'がほしい',
    reading: 'がほしい',
    romaji: 'ga hoshii',
    meaning: 'がほしい — to want something',
    partOfSpeech: '',
    example: '新しい車がほしいです。',
    exampleReading: 'あたらしい くるまが ほしいです。',
    exampleMeaning: 'I want a new car.',
    grammar: 'がほしい',
    formation: 'Noun + が + ほしいです',
    usage: 'Expresses that the speaker wants a thing or object.',
    grammarExamples: [
      { japanese: '新しい車がほしいです。', reading: 'あたらしい くるまが ほしいです。', english: 'I want a new car.' },
      { japanese: '水がほしいです。', reading: 'みずが ほしいです。', english: 'I want water.' },
    ],
    negative: 'ほしくないです',
    past: 'ほしかったです',
    pastNegative: 'ほしくなかったです',
    commonMistake: 'Use が with ほしい. For wanting to perform an action, use the たい form instead.',
    formalAlternative: '',
    interval: 0,
    repetitions: 0,
    easeFactor: 2.5,
    dueDate: Date.now(),
  },

  {
    type: 'grammar',
    category: 'Existence',
    jlpt: 'N5',
    tags: ['N5', 'grammar', 'imasu'],
    kanji: 'がいます',
    reading: 'がいます',
    romaji: 'ga imasu',
    meaning: 'がいます — there is; there are; to be (living things)',
    partOfSpeech: '',
    example: '教室に先生がいます。',
    exampleReading: 'きょうしつに せんせいが います。',
    exampleMeaning: 'There is a teacher in the classroom.',
    grammar: 'がいます',
    formation: 'Place + に + Living thing + がいます',
    usage: 'Indicates the existence or presence of people and animals.',
    grammarExamples: [
      { japanese: '教室に先生がいます。', reading: 'きょうしつに せんせいが います。', english: 'There is a teacher in the classroom.' },
      { japanese: '公園に犬がいます。', reading: 'こうえんに いぬが います。', english: 'There is a dog in the park.' },
    ],
    negative: 'いません',
    past: 'いました',
    pastNegative: 'いませんでした',
    commonMistake: 'Use います for living things and あります for non-living things.',
    formalAlternative: '',
    interval: 0,
    repetitions: 0,
    easeFactor: 2.5,
    dueDate: Date.now(),
  },

  {
    type: 'grammar',
    category: 'Advice',
    jlpt: 'N5',
    tags: ['N5', 'grammar', 'hou-ga-ii'],
    kanji: 'ほうがいい',
    reading: 'ほうがいい',
    romaji: 'hou ga ii',
    meaning: 'ほうがいい — had better; it would be better to; should',
    partOfSpeech: '',
    example: '早く寝たほうがいいです。',
    exampleReading: 'はやく ねたほうが いいです。',
    exampleMeaning: 'You should go to bed early.',
    grammar: 'ほうがいい',
    formation: 'Verb past form + ほうがいい',
    usage: 'Gives advice or recommends that someone do something.',
    grammarExamples: [
      { japanese: '早く寝たほうがいいです。', reading: 'はやく ねたほうが いいです。', english: 'You should go to bed early.' },
      { japanese: '病院へ行ったほうがいいです。', reading: 'びょういんへ いったほうが いいです。', english: 'You should go to the hospital.' },
    ],
    negative: 'ないほうがいいです',
    past: '',
    pastNegative: '',
    commonMistake: 'Although the verb is in the past form, the expression normally gives present/future advice.',
    formalAlternative: '',
    interval: 0,
    repetitions: 0,
    easeFactor: 2.5,
    dueDate: Date.now(),
  },

  {
    type: 'grammar',
    category: 'Adjectives',
    jlpt: 'N5',
    tags: ['N5', 'grammar', 'i-adjectives'],
    kanji: 'い-adjectives',
    reading: 'い-adjectives',
    romaji: 'i-adjectives',
    meaning: 'い-adjectives — adjectives ending in い',
    partOfSpeech: '',
    example: 'この本はおもしろいです。',
    exampleReading: 'この ほんは おもしろいです。',
    exampleMeaning: 'This book is interesting.',
    grammar: 'い-adjectives',
    formation: 'Adjective stem + い',
    usage: 'Japanese adjectives that normally end in い in their basic form. They can directly modify nouns and conjugate themselves.',
    grammarExamples: [
      { japanese: 'この本はおもしろいです。', reading: 'この ほんは おもしろいです。', english: 'This book is interesting.' },
      { japanese: '今日は暑くないです。', reading: 'きょうは あつくないです。', english: 'Today is not hot.' },
    ],
    negative: '～くない',
    past: '～かった',
    pastNegative: '～くなかった',
    commonMistake: 'Do not normally add だ after an い-adjective. For example, おいしいです is correct.',
    formalAlternative: '',
    interval: 0,
    repetitions: 0,
    easeFactor: 2.5,
    dueDate: Date.now(),
  },

  {
    type: 'grammar',
    category: 'Superlative',
    jlpt: 'N5',
    tags: ['N5', 'grammar', 'ichiban'],
    kanji: '一番',
    reading: 'いちばん',
    romaji: 'ichiban',
    meaning: '一番 — the most; the best',
    partOfSpeech: '',
    example: '日本料理が一番好きです。',
    exampleReading: 'にほんりょうりが いちばん すきです。',
    exampleMeaning: 'I like Japanese food the most.',
    grammar: '一番',
    formation: 'Noun + が + 一番 + adjective',
    usage: 'Used to express the highest degree or rank: the most, the best, or number one.',
    grammarExamples: [
      { japanese: '日本料理が一番好きです。', reading: 'にほんりょうりが いちばん すきです。', english: 'I like Japanese food the most.' },
      { japanese: '富士山が一番高いです。', reading: 'ふじさんが いちばん たかいです。', english: 'Mount Fuji is the highest.' },
    ],
    negative: '',
    past: '',
    pastNegative: '',
    commonMistake: '一番 means the highest degree, not simply "most" in a casual sense. Use context to determine meaning.',
    formalAlternative: '',
    interval: 0,
    repetitions: 0,
    easeFactor: 2.5,
    dueDate: Date.now(),
  },
];

async function run() {
  try {
    const mongoose = await connectDB();
    const db = mongoose.connection.db;

    const deckId = ObjectId(TARGET_DECK_ID);

    // Try top-level 'decks' collection first
    const decksColl = db.collection('decks');
    const topUpdate = await decksColl.updateOne(
      { _id: deckId },
      { $push: { cards: { $each: cards } } }
    );

    if (topUpdate.matchedCount && topUpdate.modifiedCount >= 0) {
      console.log(`Pushed ${cards.length} cards into top-level decks/${TARGET_DECK_ID}`);
      await mongoose.disconnect();
      return;
    }

    // Fallback: push into collections.decks.$.cards
    const collectionsColl = db.collection('collections');
    const collUpdate = await collectionsColl.updateOne(
      { 'decks._id': deckId },
      { $push: { 'decks.$.cards': { $each: cards } } }
    );

    if (collUpdate.matchedCount && collUpdate.modifiedCount >= 0) {
      console.log(`Pushed ${cards.length} cards into collections.decks.${TARGET_DECK_ID}`);
    } else {
      console.log(`Deck ${TARGET_DECK_ID} not found in 'decks' or nested in 'collections'.`);
    }

    await mongoose.disconnect();
  } catch (err) {
    console.error('Error updating DB:', err);
    process.exitCode = 1;
  }
}

run();