'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

export const LANGUAGES = [
  { code: 'ja', name: '日本語', flag: '🇯🇵', label: '日本語' },
  { code: 'en', name: 'English', flag: '🇺🇸', label: 'English' },
  { code: 'es', name: 'Español', flag: '🇪🇸', label: 'Español' },
  { code: 'zh', name: '中文', flag: '🇨🇳', label: '中文' },
  { code: 'ko', name: '한국어', flag: '🇰🇷', label: '한국어' },
  { code: 'fr', name: 'Français', flag: '🇫🇷', label: 'Français' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪', label: 'Deutsch' },
];

export const TRANSLATIONS = {
  ja: {
    // Brand & Header
    brandTitle: '学ぶ',
    brandSub: '日本語学習 · JLPT N5〜N1 フラッシュカード',
    examCountdownPrefix: '次回 JLPT試験まで',
    days: '日',
    hours: '時間',
    minutes: '分',
    reviewDue: '復習',
    newFolder: '新しいフォルダ',
    addFolder: '追加',
    jlptLevelLabel: 'JLPT レベル:',
    all: 'すべて',
    kana: 'かな',
    beginner: '初級',
    elementary: '基礎',
    intermediate: '中級',
    upperIntermediate: '上級',
    advanced: '最上級',
    fiftySounds: '五十音',
    language: '言語',

    // Breadcrumbs & Nav
    collections: 'コレクション',
    decks: 'デッキ',
    study: '学習',
    stats: '統計',
    quickReview: '今すぐ復習',
    back: '戻る',
    folders: 'フォルダ',

    // Collections
    collectionsPortalTitle: '日本語を極める。',
    collectionsPortalSub: '語彙 · 文法 · 漢字 · かな を網羅する分散学習',
    collectionsPortalDesc: '科学的エビングハウス忘却曲線に基づいたSRS（間隔反復学習）システム。JLPTレベルごとの学習進捗管理と、毎日の復習習慣で着実な合格を目指します。',
    totalFolders: '総フォルダ',
    totalDecks: '総デッキ',
    totalCards: '総カード数',
    collectionsList: 'コレクション一覧',
    filteringWith: 'で絞り込み中',
    searchPlaceholder: 'フォルダ・デッキ・単語を検索...',
    viewDecks: 'デッキ一覧を見る',
    otherDecksCount: '他 {n} 件のデッキ',
    navDashboard: "ダッシュボード",
    navExplore: "関係図",
    navLibrary: "読書",
    navProgress: "進捗",
    navSettings: "設定",
    navDrill: "集中ドリル",
    navExam: "模擬試験",
    startReview: "復習を開始",
    studyModes: "学習モード",
    levelHubs: "レベル別ハブ",
    credits: "権利表記",
    daysStreak: "{n}日 継続中",
    home: "ホーム",
    landingHeroHeadline: "日本語を本気で身につける、無駄のない反復学習。",
    landingHeroSub: "漢字・語彙・文法・読解がひとつのSRSキューで結びつく。科学的に証明されたSM-2アルゴリズムで、忘れかけた絶妙なタイミングに復習を届けます。",
    startLearningFree: "今すぐ無料で始める",
    loginExisting: "既存アカウントでログイン",
    login: "ログイン",
    noHiddenFees: "登録料・隠し料金なし",
    nativeTtsPitch: "音声TTS & ピッチアクセント",
    mockExamsIncluded: "JLPT模試機能付き",
    howItWorks: "3ステップで確実に定着",
    howItWorksSub: "詰め込みではなく、忘却曲線を計算した毎日の自然な習慣へ。",
    step1Title: "1. 学ぶ (Learn)",
    step1Desc: "漢字の筆順、単語のピッチアクセント、文法の接続ルールを構造的にインプット。",
    step2Title: "2. 復習する (Review)",
    step2Desc: "SM-2エンジンが最適なインターバルを算出。忘れる寸前のベストタイミングで自動出題。",
    step3Title: "3. 追跡する (Track)",
    step3Desc: "4つの柱別の記憶定着曲線とJLPT合格レディネスで、現在地と合格までの日数を可視化。",
    curriculumByLevel: "JLPT レベル別カリキュラム",
    curriculumSub: "基礎のかなから最上級N1まで、体系化されたデータセットを完全収録。",
    unlockAllLevels: "全レベルを開放する →",
    whyChooseManabu: "Manabuが選ばれる理由",
    graphDifferentiatorTitle: "関係図 (Relationship Graph)",
    graphDifferentiatorDesc: "漢字をタップすると使用単語が表示され、単語から文法へドリルダウン。孤立した暗記ではなく、知識を有機的につなげて覚えます。",
    pitchDifferentiatorTitle: "Kanjium ピッチアクセント",
    pitchDifferentiatorDesc: "平板・頭高・中高・尾高のピッチアクセント高低曲線を視覚化。自然で美しい発音を最初から身につけられます。",
    readerDifferentiatorTitle: "多読リーダー & レディネス",
    readerDifferentiatorDesc: "レベル別の読本で、知っている単語と復習キューに入っている単語を下線表示。タップで即辞書引き＆SRS追加できます。",
    unlockDifferentiatorTitle: "前提知識に応じたアンロック",
    unlockDifferentiatorDesc: "文法を学ぶために必要な前提語彙がSRSで定着するまで、文法ポイントを無理に解禁せず段階的にアンロックします。",
    privacyPolicy: "プライバシー",
    termsOfService: "利用規約",
    welcomeBack: "おかえりなさい",
    streakDays: "{n}日 連続達成",
    streakCompletedToday: "本日達成済み ✓",
    streakPendingToday: "本日まだ未達成",
    srsQueue: "SRS キュー",
    estMinutes: "所要目安: 約{n}分",
    cardsDueForReview: "枚の復習カード",
    allReviewsCompleted: "本日の復習はすべて完了！ 🎉",
    examReadiness: "合格レディネス",
    masteryLevel: "{level} 習熟度",
    readinessDesc: "SM-2定着間隔（7日以上）を満たしたカード群から総合算出されています。",
    viewFluencyProjection: "詳細な習熟予測と到達日を見る →",
    wordOfTheDay: "今日の言葉 · Word of the Day",
    reviewInQueue: "キューで復習する",
    quickDrillTitle: "弱点集中ドリル",
    quickDrillSub: "ミス優先の即時特訓",
    quickLibraryTitle: "多読リーダー",
    quickLibrarySub: "SRS下線付き読書",
    quickGraphTitle: "関係図 (Graph)",
    quickGraphSub: "漢字⇄単語⇄文法",
    quickExamTitle: "JLPT 模擬試験",
    quickExamSub: "時間計測・聴解付き",
    pause: "一時停止",
    modeRecognition: "認識",
    modeAudio: "聴解",
    modeCanvas: "手書き",
    pronounce: "発音を聞く",
    tapToReveal: "タップまたはスペースキーで裏面",
    selectRating: "評価を選択",
    keyboardShortcuts: "ショートカット: 1, 2, 3, 4",
    whyThisCard: "なぜこのカードが出題されたか (SM-2計算式)",
    currentInterval: "現在の間隔",
    easeFactor: "容易度 (Ease)",
    repetitionCount: "連続正解数",
    againBtn: "もう一度",
    hardBtn: "難しい",
    goodBtn: "正解",
    easyBtn: "簡単",
    sessionFinishedTitle: "セッション完了！",
    sessionFinishedDesc: "お疲れ様でした。記憶のインターバルが正常に更新されました。",
    reviewedCount: "復習枚数",
    accuracyRate: "正解率",
    xpEarned: "獲得XP",
    breakdown: "内訳",
    backToDashboard: "ダッシュボードへ戻る",
    reviewAgain: "もう一度復習する",
    drillModeBadge: "特訓モード (DRILL)",
    drillCompletedTitle: "ドリル終了！",
    drillCompletedDesc: "苦手カードの特訓が完了しました。SM-2スケジュールには影響しません。",
    practiceAgain: "再特訓 (Again)",
    masteredIt: "克服した (Pass)",
    levelHub: "レベル別ハブ",
    totalRegisteredCards: "登録カード計 {n} 枚",
    masteryRate: "修了率 (Mastery)",
    masterySub: "定着カード / 全カード",
    reviewLevelCards: "{level} の復習",
    viewLesson: "レッスンを見る →",
    startDrillForSet: "このセットのドリルを開始 (Start Drill)",
    locked: "ロック中",
    backToHub: "ハブへ戻る",
    commonCompounds: "代表的な熟語 (Compounds)",
    formationRule: "接続・構文 (Formation Rule)",
    nuanceCallout: "ニュアンス・使い分け (Nuance & Contrast)",
    mockExamSetup: "JLPT 総合模擬試験",
    mockExamSub: "本番の試験時間と配点基準に準拠した総合模擬試験です。",
    timeLimit: "制限時間",
    maxScore: "満点",
    passingScore: "合格基準点",
    sectionalThreshold: "基準点割れ条件",
    selectSections: "受験科目の選択 (Section Toggles)",
    beginExam: "模擬試験を開始する (Begin Exam) →",
    examPassed: "合格基準達成 (PASSED)",
    examFailed: "不合格 (NOT PASSED)",
    sectionBreakdown: "分野別得点 (Section Breakdown)",
    missedQuestions: "間違えた問題",
    addMissedToSrs: "間違えた問題をSRSに追加 (Add to SRS)",
    addedToSrs: "✓ SRSキューに追加済み",
    retakeExam: "もう一度受験する",
    nextQuestion: "次の問題 →",
    prevQuestion: "← 前の問題",
    submitExam: "試験を終了して採点する ✓",
    settingsTitle: "アカウント & 学習設定",
    profileBasics: "1. プロフィール基本情報",
    username: "ユーザー名",
    targetLevel: "目標JLPTレベル",
    examDate: "目標試験日",
    studyEnvironment: "2. 学習環境・表示設定",
    defaultSessionSize: "1セッションの標準カード数",
    furiganaDefault: "ふりがな（ルビ）のデフォルト",
    dailyReminders: "毎日の学習リマインダー通知",
    reducedMotion: "アニメーションの軽減 (Reduced Motion)",
    saveSettings: "設定を保存する",
    settingsSaved: "✓ 設定を保存しました",
    dangerZone: "3. データ管理 & デンジャーゾーン",
    exportData: "エクスポート",
    resetProgress: "リセット",
    leaderboardTitle: "週間番付 · Weekly Leaderboard",
    resetsInDays: "リセットまで: あと {n} 日",
    leaderboardPrivacy: "ランキングへの参加設定",
    makePrivate: "非公開にする",
    joinLeaderboard: "番付に参加する",
    rankUser: "順位 / 学習者",
    xpRank: "獲得XP / 段位",
    aboutTitle: "学ぶについて & 権利表記",
    whyIBuiltThis: "開発の背景 (Why I Built This)",
    openDataAttribution: "オープンデータ帰属表示 (Attribution & Licenses)",
    createAccount: "アカウント作成",
    loginTitle: "ログイン",
    emailLabel: "メールアドレス",
    takePlacementQuiz: "判定テストを受ける？",
    startLearning: "学習を開始する",
    loginAndReview: "ログインして復習へ",
    alreadyHaveAccount: "すでにアカウントをお持ちの方はこちら",
    needAccount: "初めてご利用の方はこちらから登録",
    previous: "前へ",
    next: "次へ",
    furiganaOn: "ふりがな: ON",
    furiganaOff: "ふりがな: OFF",
    drillReadyHint: "レッスン完了後に直接ドリルを開始できます",
    meaningTitle: "意味 (Meaning)",
    lessonSetLabel: "レッスンセット ({count} 項目)",
    otherDecksCount: "他 {count} 件のデッキ...",
    noDecksInFolder: '該当するデッキがありません',
    noCollectionsFound: 'デッキが見つかりません',
    noCollectionsDesc: '現在のフィルターまたは検索キーワードに一致するコレクションがありません。',
    resetFilter: 'フィルターをリセット',
    createFolderModalTitle: '新しいコレクションを作成',
    createFolderModalDesc: '日本語の教材やレベルに合わせてフォルダを作成します。',
    folderNameLabel: 'フォルダ名',
    folderNamePlaceholder: '例: N3文法マスター、Daily Kanji',
    cancel: 'キャンセル',
    createButton: 'フォルダを作成',
    creatingButton: '作成中...',

    // Dashboard
    cards: 'カード',
    dueCount: '復習期限',
    newCount: '未習熟 (新規)',
    allPillar: 'すべて',
    vocabPillar: '語彙',
    grammarPillar: '文法',
    kanjiPillar: '漢字',
    kanaPillar: '五十音',
    searchDecksPlaceholder: 'デッキや単語を検索...',
    grammarFocusTitle: '文法特化デッキ (Grammar Focus)',
    grammarPointsCount: '{n} 文法項目',
    studyAllGrammar: '{level} 文法を一括学習',
    masteryProgress: '習熟度進捗',
    studyNow: '今すぐ学習する',
    allCompleted: 'すべて完了 🎉',
    newDeckPlaceholder: '新しいデッキ名...',
    addDeckButton: 'デッキ追加',
    addingButton: '作成中',
    noDecksMatch: '条件に一致するデッキがありません',
    noDecksMatchDesc: '検索条件またはフィルターを変更してください。',

    // Study Session
    romajiToggle: 'ローマ字',
    sessionCompletedTitle: '学習セッション完了！',
    sessionCompletedDesc: 'お疲れ様でした！ 本日の復習キューがすべて終了しました。記憶の定着が進んでいます。',
    again: 'もう一度',
    good: '普通',
    easy: '簡単',
    againSub: 'Again [1]',
    goodSub: 'Good [2]',
    easySub: 'Easy [3]',
    backToDashboard: 'ダッシュボードへ戻る',
    tapToFlip: 'タップまたは Space キーで裏返す',
    revealAnswer: '答えを表示する (Reveal)',
    audioButtonTooltip: '音声を発音 (Shortcut: R)',
    onyomi: '音読み (On)',
    kunyomi: '訓読み (Kun)',
    strokes: '画数',
    strokesUnit: '画',
    formation: '接続 (Formation)',
    exampleSentence: '例文 (Example)',

    // Manage Deck
    deckSettingsTitle: 'デッキ設定 & カード編集',
    bulkImportJson: '一括インポート (JSON)',
    closeBulkImport: 'JSONインポートを閉じる',
    bulkImportDesc: 'JSON配列を直接貼り付けるか、ファイルから読み込みます。',
    selectJsonFile: 'ファイル選択 (.json)',
    importDataButton: 'データをインポート',
    addNewCard: '新規カードの追加',
    kanjiLabel: '漢字 (表記)',
    readingLabel: '読み方 (ひらがな)',
    meaningLabel: '意味・説明',
    categoryLabel: 'カテゴリ',
    jlptLevelSelect: 'JLPT レベル',
    addCardButton: 'カードを追加',
    registeredCards: '登録カード一覧',
    deleteCard: '削除',
    repetitionsCount: '復習回数',
    intervalCount: '間隔',
    noCardsFound: 'カードが見つかりません。',
  },

  en: {
    // Brand & Header
    brandTitle: 'MANABU',
    brandSub: 'Japanese Learning · JLPT N5–N1 Flashcards',
    examCountdownPrefix: 'Next JLPT Exam in',
    days: 'days',
    hours: 'hrs',
    minutes: 'mins',
    reviewDue: 'Review',
    newFolder: 'New Folder',
    addFolder: 'Add',
    jlptLevelLabel: 'JLPT Level:',
    all: 'All',
    kana: 'Kana',
    beginner: 'Beginner',
    elementary: 'Elementary',
    intermediate: 'Intermediate',
    upperIntermediate: 'Upper Int',
    advanced: 'Advanced',
    fiftySounds: 'Kana (50)',
    language: 'Language',

    // Breadcrumbs & Nav
    collections: 'Collections',
    decks: 'Decks',
    study: 'Study',
    stats: 'Stats',
    quickReview: 'Review Due',
    back: 'Back',
    folders: 'Folders',

    // Collections
    collectionsPortalTitle: 'Master Japanese.',
    collectionsPortalSub: 'Comprehensive Spaced Repetition for Vocab, Grammar, Kanji & Kana',
    collectionsPortalDesc: 'Scientifically powered by the Ebbinghaus forgetting curve with spaced repetition (SRS). Track progress across all JLPT levels and build a daily study streak toward passing.',
    totalFolders: 'Total Folders',
    totalDecks: 'Total Decks',
    totalCards: 'Total Cards',
    collectionsList: 'Collections & Folders',
    filteringWith: 'Filtered by',
    searchPlaceholder: 'Search folders, decks, words...',
    viewDecks: 'View Decks',
    otherDecksCount: '+{n} more decks',
    navDashboard: "Dashboard",
    navExplore: "Explore Graph",
    navLibrary: "Reading Library",
    navProgress: "Progress",
    navSettings: "Settings",
    navCourse: "Curriculum",
    courseRoadmap: "Curriculum",
    courseRoadmapTitle: "Japanese Learning Roadmap",
    courseRoadmapSub: "A sequenced path from writing systems through grammar patterns and contextual vocabulary.",
    totalCourseProgress: "Total Course Progress",
    lessonsCompleted: "{completed} / {total} Lessons Completed",
    continueLesson: "Continue Lesson",
    startLesson: "Start Lesson",
    reviewLesson: "Review Lesson",
    nextLesson: "Next Lesson",
    allUnits: "All Units",
    lessonCompletedBadge: "Completed",
    lessonLockedBadge: "Locked",
    lessonReadyBadge: "Available",
    prereqRequired: "Prerequisite required",
    completeLessonAndAddToSrs: "Complete Lesson & Add to SRS Reviews",
    lessonCompletedTitle: "Lesson Completed!",
    lessonCompletedDesc: "You have successfully completed this lesson.",
    xpEarned: "Experience Earned",
    cardsAddedToSrs: "Cards Added to SRS Queue",
    startSrsReviewNow: "Start SRS Review Now →",
    proceedToNextLesson: "Proceed to Next Lesson →",
    backToCurriculum: "Back to Curriculum",
    exitAndSave: "Exit & Save",
    kanaCharacters: "Kana Characters",
    grammarConcepts: "Grammar Concepts",
    contextVocab: "Vocabulary in Context",
    kanjiFundamentals: "Kanji Fundamentals",
    pronunciationHint: "Click any character to hear pronunciation",
    estTimeMinutes: "Est. ~{n} mins",
    structuredCourseBadge: "STRUCTURED COURSE",
    currentLessonPrefix: "Current Lesson",
    viewFullCurriculum: "View Full Curriculum",
    navDrill: "Adaptive Drill",
    navExam: "Mock Exam",
    startReview: "Start Review",
    studyModes: "Study Modes",
    levelHubs: "Level Hubs",
    credits: "Attribution & Licenses",
    daysStreak: "{n} Day Streak",
    home: "Home",
    landingHeroHeadline: "Master Japanese with Purpose. Zero Fluff Spaced Repetition.",
    landingHeroSub: "Kanji, vocabulary, grammar, and reading unified in one SRS queue. Powered by the scientifically proven SM-2 algorithm.",
    startLearningFree: "Start Learning Free",
    loginExisting: "Log in to existing account",
    login: "Log In",
    noHiddenFees: "Free forever · No hidden fees",
    nativeTtsPitch: "Native TTS & Pitch Accents",
    mockExamsIncluded: "Full JLPT Mock Exams",
    howItWorks: "Master Japanese in 3 Steps",
    howItWorksSub: "Not cramming, but a natural daily habit calculated against the forgetting curve.",
    step1Title: "1. Learn",
    step1Desc: "Structured input for stroke orders, pitch accents, and grammar rules.",
    step2Title: "2. Review",
    step2Desc: "SM-2 engine calculates optimal intervals, serving reviews just before you forget.",
    step3Title: "3. Track",
    step3Desc: "Visualize your current mastery and projected exam readiness across all 4 pillars.",
    curriculumByLevel: "Curriculum by JLPT Level",
    curriculumSub: "From foundational kana to advanced N1, fully structured datasets included.",
    unlockAllLevels: "Explore All Levels →",
    whyChooseManabu: "Why Learners Choose Manabu",
    graphDifferentiatorTitle: "Relationship Graph",
    graphDifferentiatorDesc: "Tap a kanji to see vocabulary, then drill into grammar points. Connect ideas instead of memorizing in isolation.",
    pitchDifferentiatorTitle: "Kanjium Pitch Accents",
    pitchDifferentiatorDesc: "Visualize pitch accent contours (Heiban, Atamadaka, etc.) for authentic Japanese pronunciation.",
    readerDifferentiatorTitle: "Graded Reader & Readiness",
    readerDifferentiatorDesc: "Read in context with active SRS words underlined. Tap any word to look up definitions and inject into reviews.",
    unlockDifferentiatorTitle: "Prerequisite Unlocking",
    unlockDifferentiatorDesc: "Grammar unlocks once prerequisite vocabulary reaches a stable SRS interval, avoiding premature struggle.",
    privacyPolicy: "Privacy",
    termsOfService: "Terms",
    welcomeBack: "Welcome back",
    streakDays: "{n} Day Streak",
    streakCompletedToday: "Completed today ✓",
    streakPendingToday: "Due today",
    srsQueue: "SRS Queue",
    estMinutes: "Est: ~{n} mins",
    cardsDueForReview: "cards due for review",
    allReviewsCompleted: "All reviews completed for today! 🎉",
    examReadiness: "Exam Readiness",
    masteryLevel: "{level} Mastery",
    readinessDesc: "Calculated from cards that have reached stable SRS intervals (7+ days).",
    viewFluencyProjection: "View detailed fluency projection →",
    wordOfTheDay: "Word of the Day",
    reviewInQueue: "Review in Queue",
    quickDrillTitle: "Adaptive Drill",
    quickDrillSub: "Mistake-focused drill",
    quickLibraryTitle: "Graded Reader",
    quickLibrarySub: "Contextual SRS reading",
    quickGraphTitle: "Relationship Graph",
    quickGraphSub: "Kanji ⇄ Vocab ⇄ Grammar",
    quickExamTitle: "JLPT Mock Exam",
    quickExamSub: "Timed test with audio",
    pause: "Pause (Esc)",
    modeRecognition: "Recognition",
    modeAudio: "Audio",
    modeCanvas: "Writing",
    pronounce: "Listen",
    tapToReveal: "Tap or press Space to flip",
    selectRating: "Select your rating",
    keyboardShortcuts: "Keys: 1, 2, 3, 4",
    whyThisCard: "Why this card was scheduled (SM-2 Formula)",
    currentInterval: "Current Interval",
    easeFactor: "Ease Factor",
    repetitionCount: "Repetitions",
    againBtn: "Again",
    hardBtn: "Hard",
    goodBtn: "Good",
    easyBtn: "Easy",
    sessionFinishedTitle: "Session Completed!",
    sessionFinishedDesc: "Great job! Your memory intervals have been updated in the SRS database.",
    reviewedCount: "Cards Reviewed",
    accuracyRate: "Accuracy",
    xpEarned: "XP Earned",
    breakdown: "Breakdown",
    backToDashboard: "Back to Dashboard",
    reviewAgain: "Review Again",
    drillModeBadge: "Drill Mode",
    drillCompletedTitle: "Drill Completed!",
    drillCompletedDesc: "Mistake drill complete. Your long-term SM-2 schedule remains unaffected.",
    practiceAgain: "Practice Again",
    masteredIt: "Mastered (Pass)",
    levelHub: "Level Hub",
    totalRegisteredCards: "{n} Total Cards",
    masteryRate: "Mastery Rate",
    masterySub: "Stable / Total Cards",
    reviewLevelCards: "Review {level}",
    viewLesson: "View Lesson →",
    startDrillForSet: "Start Drill for This Set",
    locked: "Locked",
    backToHub: "Back to Hub",
    commonCompounds: "Common Compounds",
    formationRule: "Formation Rule",
    nuanceCallout: "Nuance & Contrast",
    mockExamSetup: "JLPT Mock Examination",
    mockExamSub: "Comprehensive mock exam conforming to official JLPT time limits and section scoring.",
    timeLimit: "Time Limit",
    maxScore: "Max Score",
    passingScore: "Passing Score",
    sectionalThreshold: "Section Threshold",
    selectSections: "Select Sections",
    beginExam: "Begin Exam →",
    examPassed: "Exam Passed (PASSED)",
    examFailed: "Not Passed (NOT PASSED)",
    sectionBreakdown: "Section Breakdown",
    missedQuestions: "Missed Questions",
    addMissedToSrs: "Add Missed to SRS Queue",
    addedToSrs: "✓ Added to SRS Queue",
    retakeExam: "Retake Exam",
    nextQuestion: "Next Question →",
    prevQuestion: "← Previous Question",
    submitExam: "Submit & Grade Exam ✓",
    settingsTitle: "Account & Study Settings",
    profileBasics: "1. Profile Basics",
    username: "Username",
    targetLevel: "Target JLPT Level",
    examDate: "Target Exam Date",
    studyEnvironment: "2. Study Environment & Preferences",
    defaultSessionSize: "Default Session Size",
    furiganaDefault: "Default Furigana (Ruby)",
    dailyReminders: "Daily Study Reminders",
    reducedMotion: "Reduced Motion",
    saveSettings: "Save Settings",
    settingsSaved: "✓ Settings saved",
    dangerZone: "3. Data Management & Danger Zone",
    exportData: "Export Data",
    resetProgress: "Reset Progress",
    leaderboardTitle: "Weekly Leaderboard",
    resetsInDays: "Resets in: {n} days",
    leaderboardPrivacy: "Leaderboard Privacy",
    makePrivate: "Make Private",
    joinLeaderboard: "Join Leaderboard",
    rankUser: "Rank / Learner",
    xpRank: "XP / Rank",
    aboutTitle: "About Manabu & Legal Attribution",
    whyIBuiltThis: "Why I Built This",
    openDataAttribution: "Open Data Attribution & Licenses",
    createAccount: "Create Account",
    loginTitle: "Log In",
    emailLabel: "Email Address",
    takePlacementQuiz: "Take placement quiz?",
    startLearning: "Start Learning",
    loginAndReview: "Log In to Review",
    alreadyHaveAccount: "Already have an account? Log in",
    needAccount: "New user? Create an account",
    previous: "Previous",
    next: "Next",
    furiganaOn: "Furigana: ON",
    furiganaOff: "Furigana: OFF",
    drillReadyHint: "Start a drill right after completing the lesson",
    meaningTitle: "Meaning",
    lessonSetLabel: "Lesson Set ({count} items)",
    otherDecksCount: "and {count} more decks...",
    noDecksInFolder: 'No matching decks',
    noCollectionsFound: 'No Decks Found',
    noCollectionsDesc: 'No collections match your current level filter or search query.',
    resetFilter: 'Reset Filters',
    createFolderModalTitle: 'Create New Collection',
    createFolderModalDesc: 'Organize your study material by JLPT level, textbook, or topic.',
    folderNameLabel: 'Folder Name',
    folderNamePlaceholder: 'e.g. N3 Grammar Master, Daily Kanji',
    cancel: 'Cancel',
    createButton: 'Create Folder',
    creatingButton: 'Creating...',

    // Dashboard
    cards: 'Cards',
    dueCount: 'Due Review',
    newCount: 'New (Unlearned)',
    allPillar: 'All',
    vocabPillar: 'Vocab',
    grammarPillar: 'Grammar',
    kanjiPillar: 'Kanji',
    kanaPillar: 'Kana',
    searchDecksPlaceholder: 'Search decks and words...',
    grammarFocusTitle: 'Grammar Focus Decks',
    grammarPointsCount: '{n} grammar points',
    studyAllGrammar: 'Study All {level} Grammar',
    masteryProgress: 'Mastery Progress',
    studyNow: 'Study Now',
    allCompleted: 'All Caught Up 🎉',
    newDeckPlaceholder: 'New deck name...',
    addDeckButton: 'Add Deck',
    addingButton: 'Adding...',
    noDecksMatch: 'No Decks Match',
    noDecksMatchDesc: 'Try adjusting your search query or level filters.',

    // Study Session
    romajiToggle: 'Romaji',
    sessionCompletedTitle: 'Session Complete!',
    sessionCompletedDesc: 'Well done! All queued reviews are finished for now. Your brain is strengthening memory retention.',
    again: 'Again',
    good: 'Good',
    easy: 'Easy',
    againSub: 'Again [1]',
    goodSub: 'Good [2]',
    easySub: 'Easy [3]',
    backToDashboard: 'Back to Desk',
    tapToFlip: 'Tap or press Space to flip',
    revealAnswer: 'Reveal Answer [Space]',
    audioButtonTooltip: 'Listen Pronunciation (Shortcut: R)',
    onyomi: "On'yomi (Chinese reading)",
    kunyomi: "Kun'yomi (Japanese reading)",
    strokes: 'Strokes',
    strokesUnit: 'strokes',
    formation: 'Formation Rule',
    exampleSentence: 'Example',

    // Manage Deck
    deckSettingsTitle: 'Deck Settings & Card Editor',
    bulkImportJson: 'Bulk Import (JSON)',
    closeBulkImport: 'Close JSON Import',
    bulkImportDesc: 'Paste a JSON card array or upload a .json file.',
    selectJsonFile: 'Select File (.json)',
    importDataButton: 'Import Cards',
    addNewCard: 'Add New Card',
    kanjiLabel: 'Kanji / Expression',
    readingLabel: 'Reading (Hiragana)',
    meaningLabel: 'Meaning & Translation',
    categoryLabel: 'Category',
    jlptLevelSelect: 'JLPT Level',
    addCardButton: 'Add Card',
    registeredCards: 'Registered Cards',
    deleteCard: 'Delete',
    repetitionsCount: 'Reps',
    intervalCount: 'Interval',
    noCardsFound: 'No cards found.',
  },

  es: {
    // Brand & Header
    brandTitle: 'MANABU',
    brandSub: 'Aprendizaje de japonés · Flashcards JLPT N5–N1',
    examCountdownPrefix: 'Próximo examen JLPT en',
    days: 'días',
    hours: 'horas',
    minutes: 'min',
    reviewDue: 'Repaso',
    newFolder: 'Nueva carpeta',
    addFolder: 'Añadir',
    jlptLevelLabel: 'Nivel JLPT:',
    all: 'Todos',
    kana: 'Kana',
    beginner: 'Principiante',
    elementary: 'Básico',
    intermediate: 'Intermedio',
    upperIntermediate: 'Intermedio Alto',
    advanced: 'Avanzado',
    fiftySounds: 'Kana (50)',
    language: 'Idioma',

    // Breadcrumbs & Nav
    collections: 'Colecciones',
    decks: 'Mazos',
    study: 'Estudiar',
    stats: 'Estadísticas',
    quickReview: 'Repasar pendientes',
    back: 'Volver',
    folders: 'Carpetas',

    // Collections
    collectionsPortalTitle: 'Domina el japonés.',
    collectionsPortalSub: 'Repetición espaciada completa para Vocabulario, Gramática, Kanji y Kana',
    collectionsPortalDesc: 'Basado en el algoritmo científico de repetición espaciada (SRS). Gestiona tu progreso en todos los niveles JLPT y alcanza tus metas.',
    totalFolders: 'Carpetas',
    totalDecks: 'Mazos',
    totalCards: 'Tarjetas',
    collectionsList: 'Lista de Colecciones',
    filteringWith: 'Filtrado por',
    searchPlaceholder: 'Buscar carpetas, mazos, palabras...',
    viewDecks: 'Ver Mazos',
    otherDecksCount: '+{n} mazos más',
    navDashboard: "Panel",
    navExplore: "Grafo de relaciones",
    navLibrary: "Lectura",
    navProgress: "Progreso",
    navSettings: "Configuración",
    navDrill: "Práctica intensiva",
    navExam: "Simulacro de examen",
    startReview: "Comenzar repaso",
    studyModes: "Modos de estudio",
    levelHubs: "Centros por nivel",
    credits: "Créditos y licencias",
    daysStreak: "Racha de {n} días",
    home: "Inicio",
    landingHeroHeadline: "Domina el japonés con propósito. Repetición espaciada sin distracciones.",
    landingHeroSub: "Kanji, vocabulario, gramática y lectura unificados en una sola cola SRS. Basado en el algoritmo SM-2.",
    startLearningFree: "Empieza gratis",
    loginExisting: "Iniciar sesión",
    login: "Iniciar sesión",
    noHiddenFees: "Gratis · Sin costes ocultos",
    nativeTtsPitch: "Audio nativo y acento tonal",
    mockExamsIncluded: "Simulacros JLPT completos",
    howItWorks: "Domina el japonés en 3 pasos",
    howItWorksSub: "Sin atracones: un hábito diario natural calculado según la curva del olvido.",
    step1Title: "1. Aprender",
    step1Desc: "Entrada estructurada para orden de trazos, acentos tonales y reglas gramaticales.",
    step2Title: "2. Repasar",
    step2Desc: "El motor SM-2 calcula intervalos óptimos justo antes de que lo olvides.",
    step3Title: "3. Seguir",
    step3Desc: "Visualiza tu dominio y preparación para el examen en los 4 pilares.",
    curriculumByLevel: "Plan de estudios por nivel",
    curriculumSub: "Desde el kana básico hasta el N1 avanzado, datos completamente estructurados.",
    unlockAllLevels: "Explorar todos los niveles →",
    whyChooseManabu: "Por qué elegir Manabu",
    graphDifferentiatorTitle: "Grafo de relaciones",
    graphDifferentiatorDesc: "Toca un kanji para ver su vocabulario y profundizar en la gramática. Conecta ideas en vez de memorizar aislado.",
    pitchDifferentiatorTitle: "Acento tonal Kanjium",
    pitchDifferentiatorDesc: "Visualiza curvas de acento tonal (Heiban, Atamadaka, etc.) para una pronunciación auténtica.",
    readerDifferentiatorTitle: "Lecturas graduadas y preparación",
    readerDifferentiatorDesc: "Lee en contexto con palabras SRS activas subrayadas. Toca cualquier palabra para ver su definición y añadirla al SRS.",
    unlockDifferentiatorTitle: "Desbloqueo por prerrequisitos",
    unlockDifferentiatorDesc: "La gramática se desbloquea cuando el vocabulario previo es estable en el SRS.",
    privacyPolicy: "Privacidad",
    termsOfService: "Términos",
    welcomeBack: "Bienvenido/a de nuevo",
    streakDays: "Racha de {n} días",
    streakCompletedToday: "Completado hoy ✓",
    streakPendingToday: "Pendiente hoy",
    srsQueue: "Cola SRS",
    estMinutes: "Est: ~{n} min",
    cardsDueForReview: "tarjetas para repasar",
    allReviewsCompleted: "¡Todos los repasos completados hoy! 🎉",
    examReadiness: "Preparación para el examen",
    masteryLevel: "Dominio de {level}",
    readinessDesc: "Calculado a partir de tarjetas con intervalo SRS estable (7+ días).",
    viewFluencyProjection: "Ver proyección de fluidez detallada →",
    wordOfTheDay: "Palabra del día",
    reviewInQueue: "Repasar en cola",
    quickDrillTitle: "Práctica intensiva",
    quickDrillSub: "Práctica de errores",
    quickLibraryTitle: "Lecturas graduadas",
    quickLibrarySub: "Lectura con SRS",
    quickGraphTitle: "Grafo de relaciones",
    quickGraphSub: "Kanji ⇄ Vocabulario ⇄ Gramática",
    quickExamTitle: "Simulacro JLPT",
    quickExamSub: "Con tiempo y audio",
    pause: "Pausa (Esc)",
    modeRecognition: "Reconocimiento",
    modeAudio: "Audio",
    modeCanvas: "Escritura",
    pronounce: "Escuchar",
    tapToReveal: "Toca o presiona Espacio para voltear",
    selectRating: "Selecciona calificación",
    keyboardShortcuts: "Teclas: 1, 2, 3, 4",
    whyThisCard: "Por qué se programó esta tarjeta (Fórmula SM-2)",
    currentInterval: "Intervalo actual",
    easeFactor: "Facilidad (Ease)",
    repetitionCount: "Repeticiones",
    againBtn: "Otra vez",
    hardBtn: "Difícil",
    goodBtn: "Bien",
    easyBtn: "Fácil",
    sessionFinishedTitle: "¡Sesión completada!",
    sessionFinishedDesc: "¡Buen trabajo! Los intervalos de memoria se han actualizado en el SRS.",
    reviewedCount: "Tarjetas repasadas",
    accuracyRate: "Precisión",
    xpEarned: "XP ganada",
    breakdown: "Desglose",
    backToDashboard: "Volver al panel",
    reviewAgain: "Repasar de nuevo",
    drillModeBadge: "Modo Práctica",
    drillCompletedTitle: "¡Práctica completada!",
    drillCompletedDesc: "Práctica de errores completada. Tu programación SM-2 no se ve afectada.",
    practiceAgain: "Practicar de nuevo",
    masteredIt: "Superado",
    levelHub: "Centro de nivel",
    totalRegisteredCards: "{n} tarjetas en total",
    masteryRate: "Tasa de dominio",
    masterySub: "Tarjetas fijadas / Total",
    reviewLevelCards: "Repasar {level}",
    viewLesson: "Ver lección →",
    startDrillForSet: "Iniciar práctica de este grupo",
    locked: "Bloqueado",
    backToHub: "Volver al centro",
    commonCompounds: "Compuestos comunes",
    formationRule: "Regla de conexión",
    nuanceCallout: "Matiz y contraste",
    mockExamSetup: "Simulacro de examen JLPT",
    mockExamSub: "Simulacro completo ajustado a tiempos y puntuación oficiales del JLPT.",
    timeLimit: "Límite de tiempo",
    maxScore: "Puntuación máxima",
    passingScore: "Puntuación de pase",
    sectionalThreshold: "Mínimo por sección",
    selectSections: "Seleccionar secciones",
    beginExam: "Comenzar examen →",
    examPassed: "Aprobado (PASSED)",
    examFailed: "No aprobado (NOT PASSED)",
    sectionBreakdown: "Desglose por secciones",
    missedQuestions: "Preguntas falladas",
    addMissedToSrs: "Añadir fallos al SRS",
    addedToSrs: "✓ Añadido al SRS",
    retakeExam: "Volver a examinarse",
    nextQuestion: "Siguiente →",
    prevQuestion: "← Anterior",
    submitExam: "Finalizar y calificar ✓",
    settingsTitle: "Configuración de cuenta y estudio",
    profileBasics: "1. Información del perfil",
    username: "Nombre de usuario",
    targetLevel: "Nivel JLPT objetivo",
    examDate: "Fecha prevista del examen",
    studyEnvironment: "2. Entorno de estudio",
    defaultSessionSize: "Tarjetas por sesión",
    furiganaDefault: "Furigana por defecto",
    dailyReminders: "Recordatorios diarios",
    reducedMotion: "Reducir animaciones",
    saveSettings: "Guardar configuración",
    settingsSaved: "✓ Guardado",
    dangerZone: "3. Gestión de datos",
    exportData: "Exportar datos",
    resetProgress: "Restablecer",
    leaderboardTitle: "Clasificación semanal",
    resetsInDays: "Reinicio en: {n} días",
    leaderboardPrivacy: "Privacidad en la clasificación",
    makePrivate: "Hacer privado",
    joinLeaderboard: "Participar",
    rankUser: "Puesto / Estudiante",
    xpRank: "XP / Rango",
    aboutTitle: "Acerca de Manabu y atribución legal",
    whyIBuiltThis: "Por qué creé esto",
    openDataAttribution: "Atribución de datos abiertos y licencias",
    createAccount: "Crear cuenta",
    loginTitle: "Iniciar sesión",
    emailLabel: "Correo electrónico",
    takePlacementQuiz: "¿Hacer prueba de nivel?",
    startLearning: "Comenzar a aprender",
    loginAndReview: "Entrar y repasar",
    alreadyHaveAccount: "¿Ya tienes cuenta? Inicia sesión",
    needAccount: "¿Nuevo usuario? Regístrate",
    previous: "Anterior",
    next: "Siguiente",
    furiganaOn: "Furigana: ACTIVADO",
    furiganaOff: "Furigana: DESACTIVADO",
    drillReadyHint: "Inicia un simulacro intensivo tras completar la lección",
    meaningTitle: "Significado",
    lessonSetLabel: "Conjunto de lecciones ({count} elementos)",
    otherDecksCount: "y {count} mazos más...",
    noDecksInFolder: 'Sin mazos correspondientes',
    noCollectionsFound: 'No se encontraron colecciones',
    noCollectionsDesc: 'No hay colecciones que coincidan con los filtros actuales.',
    resetFilter: 'Restablecer filtros',
    createFolderModalTitle: 'Crear nueva colección',
    createFolderModalDesc: 'Organiza tu material por nivel JLPT o tema.',
    folderNameLabel: 'Nombre de la carpeta',
    folderNamePlaceholder: 'Ej: Gramática N3, Kanji Diario',
    cancel: 'Cancelar',
    createButton: 'Crear carpeta',
    creatingButton: 'Creando...',

    // Dashboard
    cards: 'Tarjetas',
    dueCount: 'Pendientes',
    newCount: 'Nuevas',
    allPillar: 'Todos',
    vocabPillar: 'Vocabulario',
    grammarPillar: 'Gramática',
    kanjiPillar: 'Kanji',
    kanaPillar: 'Kana',
    searchDecksPlaceholder: 'Buscar mazos y palabras...',
    grammarFocusTitle: 'Mazos de gramática especializada',
    grammarPointsCount: '{n} puntos gramaticales',
    studyAllGrammar: 'Estudiar toda la gramática {level}',
    masteryProgress: 'Progreso de dominio',
    studyNow: 'Estudiar ahora',
    allCompleted: '¡Todo al día! 🎉',
    newDeckPlaceholder: 'Nombre del nuevo mazo...',
    addDeckButton: 'Añadir mazo',
    addingButton: 'Añadiendo...',
    noDecksMatch: 'No hay mazos coincidentes',
    noDecksMatchDesc: 'Prueba cambiando los términos de búsqueda o nivel.',

    // Study Session
    romajiToggle: 'Romaji',
    sessionCompletedTitle: '¡Sesión completada!',
    sessionCompletedDesc: '¡Excelente trabajo! Has terminado todos los repasos programados por ahora.',
    again: 'Repetir',
    good: 'Bien',
    easy: 'Fácil',
    againSub: 'Again [1]',
    goodSub: 'Good [2]',
    easySub: 'Easy [3]',
    backToDashboard: 'Volver al panel',
    tapToFlip: 'Toca o pulsa Espacio para voltear',
    revealAnswer: 'Mostrar respuesta [Espacio]',
    audioButtonTooltip: 'Escuchar pronunciación (Atajo: R)',
    onyomi: "On'yomi (Lectura china)",
    kunyomi: "Kun'yomi (Lectura japonesa)",
    strokes: 'Trazos',
    strokesUnit: 'trazos',
    formation: 'Regla de formación',
    exampleSentence: 'Ejemplo',

    // Manage Deck
    deckSettingsTitle: 'Configuración y edición de tarjetas',
    bulkImportJson: 'Importar en bloque (JSON)',
    closeBulkImport: 'Cerrar importación JSON',
    bulkImportDesc: 'Pega un array JSON o sube un archivo .json.',
    selectJsonFile: 'Seleccionar archivo (.json)',
    importDataButton: 'Importar tarjetas',
    addNewCard: 'Añadir nueva tarjeta',
    kanjiLabel: 'Kanji / Expresión',
    readingLabel: 'Lectura (Hiragana)',
    meaningLabel: 'Significado',
    categoryLabel: 'Categoría',
    jlptLevelSelect: 'Nivel JLPT',
    addCardButton: 'Añadir tarjeta',
    registeredCards: 'Tarjetas registradas',
    deleteCard: 'Eliminar',
    repetitionsCount: 'Repeticiones',
    intervalCount: 'Intervalo',
    noCardsFound: 'No se encontraron tarjetas.',
  },

  zh: {
    // Brand & Header
    brandTitle: '学',
    brandSub: '日语学习 · JLPT N5〜N1 抽认卡',
    examCountdownPrefix: '距离下次 JLPT 考试还有',
    days: '天',
    hours: '小时',
    minutes: '分钟',
    reviewDue: '复习',
    newFolder: '新建文件夹',
    addFolder: '添加',
    jlptLevelLabel: 'JLPT 等级:',
    all: '全部',
    kana: '假名',
    beginner: '初级',
    elementary: '基础',
    intermediate: '中级',
    upperIntermediate: '中高级',
    advanced: '高级',
    fiftySounds: '五十音',
    language: '语言',

    // Breadcrumbs & Nav
    collections: '收藏夹',
    decks: '卡组',
    study: '学习',
    stats: '统计',
    quickReview: '立即复习',
    back: '返回',
    folders: '文件夹',

    // Collections
    collectionsPortalTitle: '精通日语。',
    collectionsPortalSub: '涵盖词汇 · 语法 · 汉字 · 假名的间隔重复学习',
    collectionsPortalDesc: '基于艾宾浩斯记忆曲线的科学SRS系统。精准追踪各JLPT等级进度，稳步通关。',
    totalFolders: '总文件夹',
    totalDecks: '总卡组',
    totalCards: '总卡片数',
    collectionsList: '收藏夹列表',
    filteringWith: '当前筛选:',
    searchPlaceholder: '搜索文件夹、卡组、单词...',
    viewDecks: '查看卡组',
    otherDecksCount: '以及其他 {n} 个卡组',
    navDashboard: "仪表板",
    navExplore: "关联图谱",
    navLibrary: "阅读文库",
    navProgress: "学习进度",
    navSettings: "设置",
    navDrill: "针对性特训",
    navExam: "模拟考试",
    startReview: "开始复习",
    studyModes: "学习模式",
    levelHubs: "等级中心",
    credits: "来源与许可归属",
    daysStreak: "连续学习 {n} 天",
    home: "首页",
    landingHeroHeadline: "真正掌握日语，高效纯粹的间隔重复学习。",
    landingHeroSub: "汉字、词汇、语法、阅读融汇于同一个SRS记忆队列。基于科学证明的SM-2算法，在遗忘临界点精准推送复习。",
    startLearningFree: "免费开始学习",
    loginExisting: "登录已有账号",
    login: "登录",
    noHiddenFees: "完全免费 · 无隐藏收费",
    nativeTtsPitch: "原生发音与声调走向",
    mockExamsIncluded: "包含JLPT全真模拟考",
    howItWorks: "3步实现持久记忆",
    howItWorksSub: "告别死记硬背，将科学计算的遗忘曲线融入每天自然的学习习惯。",
    step1Title: "1. 学习 (Learn)",
    step1Desc: "结构化输入汉字笔顺、单词声调曲线以及语法接续规则。",
    step2Title: "2. 复习 (Review)",
    step2Desc: "SM-2记忆引擎自动推算最优复习间隔，在即将遗忘的临界点精准出题。",
    step3Title: "3. 追踪 (Track)",
    step3Desc: "通过四大板块的记忆留存曲线与JLPT合格就绪度，清晰展现当前位置与备考天数。",
    curriculumByLevel: "JLPT各等级课程体系",
    curriculumSub: "从基础假名到高级N1，完整收录体系化语言数据集。",
    unlockAllLevels: "探索所有等级 →",
    whyChooseManabu: "为什么选择学ぶ",
    graphDifferentiatorTitle: "网状知识图谱",
    graphDifferentiatorDesc: "点击汉字即可查看派生词汇，再深入至相关语法句型。告别孤立死记，建立网状有机知识连接。",
    pitchDifferentiatorTitle: "声调高低走向曲线",
    pitchDifferentiatorDesc: "直观展现平板、头高、中高、尾高等声调高低走向，从零练就自然优美发音。",
    readerDifferentiatorTitle: "分级阅读与词汇就绪度",
    readerDifferentiatorDesc: "在真实语境中分级多读，SRS复习中的单词自动下划线标注。点击即可即时查词并添加入复习队列。",
    unlockDifferentiatorTitle: "前置知识依赖解锁",
    unlockDifferentiatorDesc: "在掌握必备前置词汇前，避免过早陷入语法挫败，根据词汇掌握程度逐步解锁语法点。",
    privacyPolicy: "隐私政策",
    termsOfService: "服务条款",
    welcomeBack: "欢迎回来",
    streakDays: "连续学习 {n} 天",
    streakCompletedToday: "今日已达标 ✓",
    streakPendingToday: "今日待完成",
    srsQueue: "SRS待复习队列",
    estMinutes: "预计耗时: 约{n}分钟",
    cardsDueForReview: "张待复习卡片",
    allReviewsCompleted: "今日待复习卡片已全部完成！ 🎉",
    examReadiness: "考试就绪度",
    masteryLevel: "{level} 掌握度",
    readinessDesc: "由达到SM-2长期记忆巩固标准（7天及以上）的卡片综合推算。",
    viewFluencyProjection: "查看详细流利度预测与考试日期 →",
    wordOfTheDay: "每日一词",
    reviewInQueue: "在队列中复习",
    quickDrillTitle: "针对性特训",
    quickDrillSub: "错题优先特训",
    quickLibraryTitle: "分级多读文库",
    quickLibrarySub: "带SRS下划线阅读",
    quickGraphTitle: "网状知识图谱",
    quickGraphSub: "汉字 ⇄ 词汇 ⇄ 语法",
    quickExamTitle: "JLPT全真模拟考",
    quickExamSub: "计时考核·配听力",
    pause: "暂停 (Esc)",
    modeRecognition: "认读",
    modeAudio: "听力",
    modeCanvas: "书写",
    pronounce: "播放发音",
    tapToReveal: "点击或按空格翻面",
    selectRating: "选择熟练程度",
    keyboardShortcuts: "快捷键: 1, 2, 3, 4",
    whyThisCard: "该卡片出题依据 (SM-2计算公式)",
    currentInterval: "当前间隔",
    easeFactor: "难度系数 (Ease)",
    repetitionCount: "连续正确次数",
    againBtn: "重来",
    hardBtn: "较难",
    goodBtn: "良好",
    easyBtn: "容易",
    sessionFinishedTitle: "复习环节完成！",
    sessionFinishedDesc: "干得漂亮！您的记忆遗忘间隔已在SRS数据库中成功更新。",
    reviewedCount: "复习张数",
    accuracyRate: "正确率",
    xpEarned: "获得经验",
    breakdown: "分类明细",
    backToDashboard: "返回控制面板",
    reviewAgain: "再次复习",
    drillModeBadge: "特训模式",
    drillCompletedTitle: "特训结束！",
    drillCompletedDesc: "针对性强化已完成。此练习不会打乱长期SM-2正常复习计划。",
    practiceAgain: "继续强化",
    masteredIt: "已攻克",
    levelHub: "等级中心",
    totalRegisteredCards: "共收录 {n} 张卡片",
    masteryRate: "掌握率",
    masterySub: "长期巩固 / 总数",
    reviewLevelCards: "复习 {level}",
    viewLesson: "进入课程 →",
    startDrillForSet: "开始该组特训",
    locked: "未解锁",
    backToHub: "返回等级中心",
    commonCompounds: "常用熟语·复合词",
    formationRule: "接续法与句型",
    nuanceCallout: "语感与辨析",
    mockExamSetup: "JLPT 全真模拟考试",
    mockExamSub: "严格按照JLPT官方考试时间与各科目评分标准构建的综合模拟考试。",
    timeLimit: "考试时间",
    maxScore: "满分",
    passingScore: "及格线",
    sectionalThreshold: "单科及格门槛",
    selectSections: "选择应试科目",
    beginExam: "开始模拟考试 →",
    examPassed: "通过考试 (PASSED)",
    examFailed: "未通过考试 (NOT PASSED)",
    sectionBreakdown: "各科单项得分",
    missedQuestions: "错题列表",
    addMissedToSrs: "将错题一键导入SRS复习队列",
    addedToSrs: "✓ 已成功加入SRS队列",
    retakeExam: "重新模拟考试",
    nextQuestion: "下一题 →",
    prevQuestion: "← 上一题",
    submitExam: "交卷并查看成绩 ✓",
    settingsTitle: "账户与学习设置",
    profileBasics: "1. 个人资料",
    username: "用户名",
    targetLevel: "目标JLPT等级",
    examDate: "考试日期",
    studyEnvironment: "2. 学习环境与偏好",
    defaultSessionSize: "单次复习卡片上限",
    furiganaDefault: "假名注音默认显示",
    dailyReminders: "每日学习提醒",
    reducedMotion: "减少界面动效",
    saveSettings: "保存设置",
    settingsSaved: "✓ 设置已保存",
    dangerZone: "3. 数据管理与危险操作",
    exportData: "导出数据",
    resetProgress: "重置进度",
    leaderboardTitle: "周榜排名",
    resetsInDays: "距重置还剩: {n} 天",
    leaderboardPrivacy: "排行榜参与公开设置",
    makePrivate: "设为私密",
    joinLeaderboard: "加入周榜",
    rankUser: "排名 / 学习者",
    xpRank: "获得经验 / 段位",
    aboutTitle: "关于学ぶ与版权许可声明",
    whyIBuiltThis: "项目发起初衷",
    openDataAttribution: "开源语言学数据项目归属",
    createAccount: "创建账号",
    loginTitle: "登录",
    emailLabel: "电子邮箱",
    takePlacementQuiz: "参加定级测试？",
    startLearning: "进入学习",
    loginAndReview: "登录并继续复习",
    alreadyHaveAccount: "已有账号？点此登录",
    needAccount: "初次使用？免费注册",
    previous: "上一页",
    next: "下一页",
    furiganaOn: "假名注音: 开",
    furiganaOff: "假名注音: 关",
    drillReadyHint: "学完后可立即开始定向特训",
    meaningTitle: "含义",
    lessonSetLabel: "课程集 ({count} 项)",
    otherDecksCount: "以及另外 {count} 个卡组...",
    noDecksInFolder: '无符合条件的卡组',
    noCollectionsFound: '未找到卡组',
    noCollectionsDesc: '没有与当前等级或搜索词匹配的卡组。',
    resetFilter: '重置筛选',
    createFolderModalTitle: '创建新文件夹',
    createFolderModalDesc: '按教材或等级整理您的学习材料。',
    folderNameLabel: '文件夹名称',
    folderNamePlaceholder: '例如: N3语法特训, 常用汉字',
    cancel: '取消',
    createButton: '创建文件夹',
    creatingButton: '创建中...',

    // Dashboard
    cards: '卡片',
    dueCount: '待复习',
    newCount: '新卡片 (未学)',
    allPillar: '全部',
    vocabPillar: '词汇',
    grammarPillar: '语法',
    kanjiPillar: '汉字',
    kanaPillar: '五十音',
    searchDecksPlaceholder: '搜索卡组和单词...',
    grammarFocusTitle: '文法特化卡组',
    grammarPointsCount: '{n} 个语法项',
    studyAllGrammar: '一键学习 {level} 语法',
    masteryProgress: '掌握进度',
    studyNow: '开始学习',
    allCompleted: '全部完成 🎉',
    newDeckPlaceholder: '新卡组名称...',
    addDeckButton: '添加卡组',
    addingButton: '添加中...',
    noDecksMatch: '没有匹配的卡组',
    noDecksMatchDesc: '请尝试更改搜索词或等级筛选。',

    // Study Session
    romajiToggle: '罗马字',
    sessionCompletedTitle: '学习已完成！',
    sessionCompletedDesc: '辛苦了！本次复习队列已全部完成，记忆正在加深。',
    again: '重来',
    good: '良好',
    easy: '简单',
    againSub: 'Again [1]',
    goodSub: 'Good [2]',
    easySub: 'Easy [3]',
    backToDashboard: '返回桌面',
    tapToFlip: '点击或按空格键翻转',
    revealAnswer: '显示答案 [空格]',
    audioButtonTooltip: '朗读发音 (快捷键: R)',
    onyomi: '音读 (On)',
    kunyomi: '训读 (Kun)',
    strokes: '笔画数',
    strokesUnit: '画',
    formation: '接续规则 (Formation)',
    exampleSentence: '例句 (Example)',

    // Manage Deck
    deckSettingsTitle: '卡组设置与卡片编辑',
    bulkImportJson: '批量导入 (JSON)',
    closeBulkImport: '关闭批量导入',
    bulkImportDesc: '直接粘贴 JSON 数组或上传 .json 文件。',
    selectJsonFile: '选择文件 (.json)',
    importDataButton: '导入卡片',
    addNewCard: '添加新卡片',
    kanjiLabel: '汉字 / 词汇',
    readingLabel: '读音 (平假名)',
    meaningLabel: '含义与翻译',
    categoryLabel: '分类',
    jlptLevelSelect: 'JLPT 等级',
    addCardButton: '添加卡片',
    registeredCards: '已登记卡片',
    deleteCard: '删除',
    repetitionsCount: '复习次数',
    intervalCount: '间隔天数',
    noCardsFound: '未找到卡片。',
  },

  ko: {
    // Brand & Header
    brandTitle: '배움 (学)',
    brandSub: '일본어 학습 · JLPT N5~N1 플래시카드',
    examCountdownPrefix: '다음 JLPT 시험까지',
    days: '일',
    hours: '시간',
    minutes: '분',
    reviewDue: '복습',
    newFolder: '새 폴더',
    addFolder: '추가',
    jlptLevelLabel: 'JLPT 레벨:',
    all: '전체',
    kana: '가나',
    beginner: '초급',
    elementary: '기초',
    intermediate: '중급',
    upperIntermediate: '준상급',
    advanced: '상급',
    fiftySounds: '오십음도',
    language: '언어',

    // Breadcrumbs & Nav
    collections: '컬렉션',
    decks: '덱',
    study: '학습',
    stats: '통계',
    quickReview: '지금 복습',
    back: '뒤로',
    folders: '폴더',

    // Collections
    collectionsPortalTitle: '일본어를 마스터하다.',
    collectionsPortalSub: '어휘 · 문법 · 한자 · 가나를 아우르는 분산 반복 학습',
    collectionsPortalDesc: '에빙하우스 망각곡선 기반의 SRS 시스템으로 효율적으로 암기하세요.',
    totalFolders: '총 폴더',
    totalDecks: '총 덱',
    totalCards: '총 카드 수',
    collectionsList: '컬렉션 목록',
    filteringWith: '필터링 중:',
    searchPlaceholder: '폴더, 덱, 단어 검색...',
    viewDecks: '덱 목록 보기',
    otherDecksCount: '외 {n}개 덱',
    navDashboard: "대시보드",
    navExplore: "관계도",
    navLibrary: "독서",
    navProgress: "학습 진도",
    navSettings: "설정",
    navDrill: "집중 드릴",
    navExam: "모의시험",
    startReview: "복습 시작",
    studyModes: "학습 모드",
    levelHubs: "레벨별 허브",
    credits: "저작권 및 라이선스",
    daysStreak: "{n}일 연속 달성",
    home: "홈",
    landingHeroHeadline: "군더더기 없는 간격 반복 학습으로 진짜 일본어를 마스터하세요.",
    landingHeroSub: "한자, 어휘, 문법, 독해가 하나의 SRS 큐로 연결됩니다. 과학적으로 검증된 SM-2 알고리즘으로 잊기 직전에 복습을 전달합니다.",
    startLearningFree: "무료로 시작하기",
    loginExisting: "기존 계정으로 로그인",
    login: "로그인",
    noHiddenFees: "숨은 요금 없음 · 평생 무료",
    nativeTtsPitch: "음성 TTS & 피치 악센트",
    mockExamsIncluded: "JLPT 모의시험 포함",
    howItWorks: "3단계로 확실하게 정착",
    howItWorksSub: "벼락치기가 아닌, 망각곡선을 계산한 매일의 자연스러운 습관으로.",
    step1Title: "1. 배우기 (Learn)",
    step1Desc: "한자의 획순, 단어의 피치 악센트, 문법 접속 규칙을 체계적으로 습득합니다.",
    step2Title: "2. 복습하기 (Review)",
    step2Desc: "SM-2 엔진이 최적의 간격을 계산하여 잊어버리기 직전 최적의 타이밍에 출제합니다.",
    step3Title: "3. 추적하기 (Track)",
    step3Desc: "4대 기둥별 기억 정착 곡선과 JLPT 합격 레디니스로 현재 위치와 남은 일수를 시각화합니다.",
    curriculumByLevel: "JLPT 레벨별 커리큘럼",
    curriculumSub: "기초 가나부터 최고급 N1까지 체계화된 데이터셋을 완전 수록.",
    unlockAllLevels: "전체 레벨 둘러보기 →",
    whyChooseManabu: "Manabu를 선택하는 이유",
    graphDifferentiatorTitle: "지식 관계망 그래프",
    graphDifferentiatorDesc: "한자를 탭하면 사용 단어가 표시되고, 단어에서 문법으로 드릴다운됩니다. 고립된 암기가 아닌 지식을 유기적으로 연결합니다.",
    pitchDifferentiatorTitle: "피치 악센트 시각화",
    pitchDifferentiatorDesc: "헤이반, 아타마다카 등 피치 악센트 고저 곡선을 시각화하여 자연스러운 발음을 익힙니다.",
    readerDifferentiatorTitle: "다독 리더 & 준비도",
    readerDifferentiatorDesc: "레벨별 독본에서 알고 있는 단어와 SRS 복습 중인 단어를 밑줄 표시. 탭하여 즉시 사전 조회 및 SRS 추가.",
    unlockDifferentiatorTitle: "선수 지식 연계 잠금해제",
    unlockDifferentiatorDesc: "문법 학습에 필요한 선수 어휘가 SRS로 정착할 때까지 무리하게 열지 않고 단계별로 잠금 해제합니다.",
    privacyPolicy: "개인정보처리방침",
    termsOfService: "이용약관",
    welcomeBack: "돌아오신 것을 환영합니다",
    streakDays: "{n}일 연속 달성",
    streakCompletedToday: "오늘 달성 완료 ✓",
    streakPendingToday: "오늘 미달성",
    srsQueue: "SRS 큐",
    estMinutes: "예상 소요시간: 약 {n}분",
    cardsDueForReview: "장의 복습 카드",
    allReviewsCompleted: "오늘의 복습이 모두 완료되었습니다! 🎉",
    examReadiness: "합격 레디니스",
    masteryLevel: "{level} 숙련도",
    readinessDesc: "SM-2 안정 간격(7일 이상)을 충족한 카드군을 바탕으로 종합 산출됩니다.",
    viewFluencyProjection: "상세 숙련도 예측 및 달성일 보기 →",
    wordOfTheDay: "오늘의 단어",
    reviewInQueue: "큐에서 복습하기",
    quickDrillTitle: "집중 드릴",
    quickDrillSub: "오답 우선 집중 훈련",
    quickLibraryTitle: "다독 리더",
    quickLibrarySub: "SRS 밑줄 지원 독서",
    quickGraphTitle: "지식 관계망 그래프",
    quickGraphSub: "한자 ⇄ 단어 ⇄ 문법",
    quickExamTitle: "JLPT 모의시험",
    quickExamSub: "시간 측정·청해 지원",
    pause: "일시정지 (Esc)",
    modeRecognition: "인식",
    modeAudio: "청해",
    modeCanvas: "필기",
    pronounce: "발음 듣기",
    tapToReveal: "탭하거나 스페이스바로 뒤집기",
    selectRating: "평가 선택",
    keyboardShortcuts: "단축키: 1, 2, 3, 4",
    whyThisCard: "이 카드가 출제된 이유 (SM-2 계산식)",
    currentInterval: "현재 간격",
    easeFactor: "용이도 (Ease)",
    repetitionCount: "연속 정답 수",
    againBtn: "다시",
    hardBtn: "어려움",
    goodBtn: "알맞음",
    easyBtn: "쉬움",
    sessionFinishedTitle: "세션 완료!",
    sessionFinishedDesc: "수고하셨습니다! 기억 간격이 SRS 데이터베이스에 정상 업데이트되었습니다.",
    reviewedCount: "복습 카드 수",
    accuracyRate: "정답률",
    xpEarned: "획득 XP",
    breakdown: "상세 내역",
    backToDashboard: "대시보드로 돌아가기",
    reviewAgain: "다시 복습하기",
    drillModeBadge: "특훈 모드",
    drillCompletedTitle: "드릴 종료!",
    drillCompletedDesc: "취약 카드 특훈이 완료되었습니다. 장기 SM-2 일정에는 영향을 주지 않습니다.",
    practiceAgain: "재훈련",
    masteredIt: "극복 완료",
    levelHub: "레벨별 허브",
    totalRegisteredCards: "등록 카드 총 {n}장",
    masteryRate: "숙련도",
    masterySub: "정착 카드 / 전체 카드",
    reviewLevelCards: "{level} 복습",
    viewLesson: "레슨 보기 →",
    startDrillForSet: "이 세트의 드릴 시작",
    locked: "잠김",
    backToHub: "허브로 돌아가기",
    commonCompounds: "대표 숙어",
    formationRule: "접속 및 구문 규칙",
    nuanceCallout: "뉘앙스 및 쓰임새 구분",
    mockExamSetup: "JLPT 모의시험",
    mockExamSub: "실제 시험 시간과 배점 기준에 맞춘 종합 모의시험입니다.",
    timeLimit: "제한 시간",
    maxScore: "만점",
    passingScore: "합격 기준 점수",
    sectionalThreshold: "과락 기준",
    selectSections: "시험 과목 선택",
    beginExam: "모의시험 시작하기 →",
    examPassed: "합격 기준 달성 (PASSED)",
    examFailed: "불합격 (NOT PASSED)",
    sectionBreakdown: "분야별 득점",
    missedQuestions: "틀린 문제",
    addMissedToSrs: "틀린 문제를 SRS에 추가",
    addedToSrs: "✓ SRS 큐에 추가됨",
    retakeExam: "다시 응시하기",
    nextQuestion: "다음 문제 →",
    prevQuestion: "← 이전 문제",
    submitExam: "시험 종료 및 채점 ✓",
    settingsTitle: "계정 및 학습 설정",
    profileBasics: "1. 기본 프로필",
    username: "사용자 이름",
    targetLevel: "목표 JLPT 레벨",
    examDate: "시험 목표일",
    studyEnvironment: "2. 학습 환경 및 표시 설정",
    defaultSessionSize: "1회 세션당 기본 카드 수",
    furiganaDefault: "후리가나(루비) 기본값",
    dailyReminders: "매일 학습 알림",
    reducedMotion: "애니메이션 줄이기",
    saveSettings: "설정 저장하기",
    settingsSaved: "✓ 설정이 저장되었습니다",
    dangerZone: "3. 데이터 관리 & 위험 구역",
    exportData: "내보내기",
    resetProgress: "진도 초기화",
    leaderboardTitle: "주간 랭킹",
    resetsInDays: "초기화까지: {n}일 남음",
    leaderboardPrivacy: "랭킹 참여 설정",
    makePrivate: "비공개로 전환",
    joinLeaderboard: "랭킹에 참여하기",
    rankUser: "순위 / 학습자",
    xpRank: "획득 XP / 단위",
    aboutTitle: "Manabu 소개 및 저작권 표기",
    whyIBuiltThis: "개발 배경 (Why I Built This)",
    openDataAttribution: "오픈 데이터 출처 표기",
    createAccount: "계정 만들기",
    loginTitle: "로그인",
    emailLabel: "이메일 주소",
    takePlacementQuiz: "레벨 판정 테스트 받기",
    startLearning: "학습 시작하기",
    loginAndReview: "로그인하고 복습하기",
    alreadyHaveAccount: "이미 계정이 있으신가요? 로그인",
    needAccount: "처음이신가요? 회원가입",
    previous: "이전",
    next: "다음",
    furiganaOn: "후리가나: 켜짐",
    furiganaOff: "후리가나: 꺼짐",
    drillReadyHint: "레슨 완료 후 바로 집중 드릴을 시작할 수 있습니다",
    meaningTitle: "의미",
    lessonSetLabel: "레슨 세트 ({count}개 항목)",
    otherDecksCount: "외 {count}개 덱...",
    noDecksInFolder: '일치하는 덱이 없습니다',
    noCollectionsFound: '덱을 찾을 수 없습니다',
    noCollectionsDesc: '현재 필터 또는 검색어와 일치하는 컬렉션이 없습니다.',
    resetFilter: '필터 초기화',
    createFolderModalTitle: '새 컬렉션 생성',
    createFolderModalDesc: '교재나 JLPT 레벨에 맞춰 폴더를 만드세요.',
    folderNameLabel: '폴더 이름',
    folderNamePlaceholder: '예: N3 문법 마스터, 일상 한자',
    cancel: '취소',
    createButton: '폴더 생성',
    creatingButton: '생성 중...',

    // Dashboard
    cards: '카드',
    dueCount: '복습 대기',
    newCount: '신규 카드',
    allPillar: '전체',
    vocabPillar: '어휘',
    grammarPillar: '문법',
    kanjiPillar: '한자',
    kanaPillar: '가나',
    searchDecksPlaceholder: '덱과 단어 검색...',
    grammarFocusTitle: '문법 특화 덱',
    grammarPointsCount: '{n}개 문법 항목',
    studyAllGrammar: '{level} 문법 모아보기',
    masteryProgress: '숙련도 진행률',
    studyNow: '지금 학습하기',
    allCompleted: '모두 완료 🎉',
    newDeckPlaceholder: '새 덱 이름...',
    addDeckButton: '덱 추가',
    addingButton: '추가 중...',
    noDecksMatch: '일치하는 덱이 없습니다',
    noDecksMatchDesc: '검색어나 필터를 변경해 보세요.',

    // Study Session
    romajiToggle: '로마자',
    sessionCompletedTitle: '학습 세션 완료!',
    sessionCompletedDesc: '수고하셨습니다! 오늘의 복습 큐가 모두 끝났습니다.',
    again: '다시',
    good: '알맞음',
    easy: '쉬움',
    againSub: 'Again [1]',
    goodSub: 'Good [2]',
    easySub: 'Easy [3]',
    backToDashboard: '대시보드로 돌아가기',
    tapToFlip: '탭하거나 스페이스바로 뒤집기',
    revealAnswer: '정답 확인 [스페이스]',
    audioButtonTooltip: '발음 듣기 (단축키: R)',
    onyomi: '음독 (On)',
    kunyomi: '훈독 (Kun)',
    strokes: '획수',
    strokesUnit: '획',
    formation: '접속 규칙',
    exampleSentence: '예문',

    // Manage Deck
    deckSettingsTitle: '덱 설정 및 카드 관리',
    bulkImportJson: '대량 가져오기 (JSON)',
    closeBulkImport: 'JSON 가져오기 닫기',
    bulkImportDesc: 'JSON 배열을 직접 붙여넣거나 파일을 업로드하세요.',
    selectJsonFile: '파일 선택 (.json)',
    importDataButton: '카드 가져오기',
    addNewCard: '새 카드 추가',
    kanjiLabel: '한자 / 표기',
    readingLabel: '읽는 법 (히라가나)',
    meaningLabel: '의미 및 번역',
    categoryLabel: '카테고리',
    jlptLevelSelect: 'JLPT 레벨',
    addCardButton: '카드 추가',
    registeredCards: '등록된 카드',
    deleteCard: '삭제',
    repetitionsCount: '복습 횟수',
    intervalCount: '간격',
    noCardsFound: '카드가 없습니다.',
  },

  fr: {
    // Brand & Header
    brandTitle: 'MANABU',
    brandSub: 'Apprentissage du japonais · Cartes mémoire JLPT N5–N1',
    examCountdownPrefix: 'Prochain examen JLPT dans',
    days: 'jours',
    hours: 'h',
    minutes: 'min',
    reviewDue: 'Révision',
    newFolder: 'Nouveau dossier',
    addFolder: 'Ajouter',
    jlptLevelLabel: 'Niveau JLPT :',
    all: 'Tous',
    kana: 'Kana',
    beginner: 'Débutant',
    elementary: 'Élémentaire',
    intermediate: 'Intermédiaire',
    upperIntermediate: 'Intermédiaire sup.',
    advanced: 'Avancé',
    fiftySounds: 'Kana (50)',
    language: 'Langue',

    // Breadcrumbs & Nav
    collections: 'Collections',
    decks: 'Paquets',
    study: 'Étudier',
    stats: 'Statistiques',
    quickReview: 'Réviser les dus',
    back: 'Retour',
    folders: 'Dossiers',

    // Collections
    collectionsPortalTitle: 'Maîtrisez le japonais.',
    collectionsPortalSub: 'Répétition espacée complète pour le vocabulaire, la grammaire, les kanjis et les kanas',
    collectionsPortalDesc: 'Basé sur la courbe d’oubli d’Ebbinghaus (SRS). Suivez vos progrès à travers tous les niveaux JLPT.',
    totalFolders: 'Dossiers',
    totalDecks: 'Paquets',
    totalCards: 'Cartes',
    collectionsList: 'Liste des collections',
    filteringWith: 'Filtré par',
    searchPlaceholder: 'Rechercher dossiers, paquets, mots...',
    viewDecks: 'Voir les paquets',
    otherDecksCount: '+{n} autres paquets',
    navDashboard: "Tableau de bord",
    navExplore: "Graphe",
    navLibrary: "Bibliothèque",
    navProgress: "Progrès",
    navSettings: "Paramètres",
    navDrill: "Entraînement",
    navExam: "Examen blanc",
    startReview: "Démarrer la révision",
    studyModes: "Modes d'étude",
    levelHubs: "Hubs de niveau",
    credits: "Crédits et licences",
    daysStreak: "{n} jours consécutifs",
    home: "Accueil",
    landingHeroHeadline: "Maîtrisez le japonais avec rigueur. Répétition espacée épurée.",
    landingHeroSub: "Kanji, vocabulaire, grammaire et lecture réunis dans une seule file SRS. Propulsé par l'algorithme éprouvé SM-2.",
    startLearningFree: "Commencer gratuitement",
    loginExisting: "Se connecter",
    login: "Connexion",
    noHiddenFees: "Gratuit · Sans frais cachés",
    nativeTtsPitch: "Synthèse vocale et accent de hauteur",
    mockExamsIncluded: "Examens blancs JLPT inclus",
    howItWorks: "Maîtrisez en 3 étapes",
    howItWorksSub: "Pas de bachotage : une habitude quotidienne naturelle calculée selon la courbe de l'oubli.",
    step1Title: "1. Apprendre",
    step1Desc: "Apprentissage structuré de l'ordre des traits, des accents et des règles.",
    step2Title: "2. Réviser",
    step2Desc: "Le moteur SM-2 calcule les intervalles optimaux juste avant l'oubli.",
    step3Title: "3. Suivre",
    step3Desc: "Visualisez votre maîtrise et votre préparation sur les 4 piliers.",
    curriculumByLevel: "Programme par niveau",
    curriculumSub: "Du kana de base au N1 avancé, jeux de données structurés inclus.",
    unlockAllLevels: "Explorer tous les niveaux →",
    whyChooseManabu: "Pourquoi choisir Manabu",
    graphDifferentiatorTitle: "Graphe de relations",
    graphDifferentiatorDesc: "Touchez un kanji pour voir le vocabulaire et approfondir la grammaire. Reliez les idées sans mémoriser isolément.",
    pitchDifferentiatorTitle: "Accents de hauteur Kanjium",
    pitchDifferentiatorDesc: "Visualisez les contours d'accent de hauteur pour une prononciation naturelle.",
    readerDifferentiatorTitle: "Lectures graduées & préparation",
    readerDifferentiatorDesc: "Lisez en contexte avec les mots SRS actifs soulignés. Touchez n'importe quel mot pour voir sa définition et l'ajouter.",
    unlockDifferentiatorTitle: "Déblocage par prérequis",
    unlockDifferentiatorDesc: "La grammaire se débloque dès que le vocabulaire prérequis est stabilisé dans le SRS.",
    privacyPolicy: "Confidentialité",
    termsOfService: "Conditions",
    welcomeBack: "Bon retour",
    streakDays: "{n} jours consécutifs",
    streakCompletedToday: "Terminé aujourd'hui ✓",
    streakPendingToday: "À faire aujourd'hui",
    srsQueue: "File SRS",
    estMinutes: "Durée est: ~{n} min",
    cardsDueForReview: "cartes à réviser",
    allReviewsCompleted: "Toutes les révisions sont terminées ! 🎉",
    examReadiness: "Préparation à l'examen",
    masteryLevel: "Maîtrise de {level}",
    readinessDesc: "Calculé à partir des cartes ayant atteint un intervalle SRS stable (7+ jours).",
    viewFluencyProjection: "Voir la projection de maîtrise détaillée →",
    wordOfTheDay: "Mot du jour",
    reviewInQueue: "Réviser dans la file",
    quickDrillTitle: "Entraînement",
    quickDrillSub: "Ciblé sur les erreurs",
    quickLibraryTitle: "Lectures graduées",
    quickLibrarySub: "Lecture intégrée SRS",
    quickGraphTitle: "Graphe",
    quickGraphSub: "Kanji ⇄ Vocabulaire ⇄ Grammaire",
    quickExamTitle: "Examen blanc JLPT",
    quickExamSub: "Chronométré avec audio",
    pause: "Pause (Échap)",
    modeRecognition: "Reconnaissance",
    modeAudio: "Audio",
    modeCanvas: "Écriture",
    pronounce: "Écouter",
    tapToReveal: "Touchez ou Espace pour retourner",
    selectRating: "Choisissez votre note",
    keyboardShortcuts: "Touches: 1, 2, 3, 4",
    whyThisCard: "Pourquoi cette carte a été planifiée (Formule SM-2)",
    currentInterval: "Intervalle actuel",
    easeFactor: "Facteur d'aisance",
    repetitionCount: "Répétitions",
    againBtn: "À revoir",
    hardBtn: "Difficile",
    goodBtn: "Bien",
    easyBtn: "Facile",
    sessionFinishedTitle: "Session terminée !",
    sessionFinishedDesc: "Bravo ! Vos intervalles de mémoire ont été mis à jour dans le SRS.",
    reviewedCount: "Cartes révisées",
    accuracyRate: "Précision",
    xpEarned: "XP gagnés",
    breakdown: "Répartition",
    backToDashboard: "Retour au tableau de bord",
    reviewAgain: "Réviser à nouveau",
    drillModeBadge: "Mode Entraînement",
    drillCompletedTitle: "Entraînement terminé !",
    drillCompletedDesc: "Entraînement terminé. Votre calendrier SM-2 à long terme reste inchangé.",
    practiceAgain: "Pratiquer encore",
    masteredIt: "Maîtrisé",
    levelHub: "Hub de niveau",
    totalRegisteredCards: "{n} cartes au total",
    masteryRate: "Taux de maîtrise",
    masterySub: "Cartes stables / Total",
    reviewLevelCards: "Réviser {level}",
    viewLesson: "Voir la leçon →",
    startDrillForSet: "Démarrer l'entraînement",
    locked: "Verrouillé",
    backToHub: "Retour au hub",
    commonCompounds: "Mots composés courants",
    formationRule: "Règle de formation",
    nuanceCallout: "Nuance et comparaison",
    mockExamSetup: "Examen blanc JLPT",
    mockExamSub: "Examen blanc complet conforme aux durées et barèmes officiels du JLPT.",
    timeLimit: "Durée",
    maxScore: "Score maximum",
    passingScore: "Score de réussite",
    sectionalThreshold: "Seuil par section",
    selectSections: "Sélectionner les sections",
    beginExam: "Commencer l'examen →",
    examPassed: "Examen réussi (PASSED)",
    examFailed: "Échoué (NOT PASSED)",
    sectionBreakdown: "Détail par section",
    missedQuestions: "Questions manquées",
    addMissedToSrs: "Ajouter les erreurs au SRS",
    addedToSrs: "✓ Ajouté au SRS",
    retakeExam: "Repasser l'examen",
    nextQuestion: "Question suivante →",
    prevQuestion: "← Question précédente",
    submitExam: "Terminer et noter ✓",
    settingsTitle: "Paramètres du compte et d'étude",
    profileBasics: "1. Profil",
    username: "Nom d'utilisateur",
    targetLevel: "Niveau JLPT cible",
    examDate: "Date de l'examen",
    studyEnvironment: "2. Préférences d'étude",
    defaultSessionSize: "Nombre de cartes par session",
    furiganaDefault: "Furigana par défaut",
    dailyReminders: "Rappels quotidiens",
    reducedMotion: "Réduire les animations",
    saveSettings: "Enregistrer les paramètres",
    settingsSaved: "✓ Paramètres enregistrés",
    dangerZone: "3. Gestion des données",
    exportData: "Exporter les données",
    resetProgress: "Réinitialiser",
    leaderboardTitle: "Classement hebdomadaire",
    resetsInDays: "Réinitialisation dans: {n} jours",
    leaderboardPrivacy: "Confidentialité du classement",
    makePrivate: "Rendre privé",
    joinLeaderboard: "Participer au classement",
    rankUser: "Rang / Apprenant",
    xpRank: "XP / Rang",
    aboutTitle: "À propos de Manabu & Mentions légales",
    whyIBuiltThis: "Pourquoi ce projet",
    openDataAttribution: "Attribution des données ouvertes",
    createAccount: "Créer un compte",
    loginTitle: "Connexion",
    emailLabel: "Adresse e-mail",
    takePlacementQuiz: "Passer le test de niveau ?",
    startLearning: "Commencer l'apprentissage",
    loginAndReview: "Se connecter et réviser",
    alreadyHaveAccount: "Déjà un compte ? Se connecter",
    needAccount: "Nouveau ? Créer un compte",
    previous: "Précédent",
    next: "Suivant",
    furiganaOn: "Furigana: ACTIVÉ",
    furiganaOff: "Furigana: DÉSACTIVÉ",
    drillReadyHint: "Démarrez un entraînement ciblé dès la fin de la leçon",
    meaningTitle: "Signification",
    lessonSetLabel: "Ensemble de leçons ({count} éléments)",
    otherDecksCount: "et {count} autres paquets...",
    noDecksInFolder: 'Aucun paquet correspondant',
    noCollectionsFound: 'Aucune collection trouvée',
    noCollectionsDesc: 'Aucune collection ne correspond à vos filtres.',
    resetFilter: 'Réinitialiser',
    createFolderModalTitle: 'Créer une nouvelle collection',
    createFolderModalDesc: 'Organisez vos cartes par niveau JLPT ou thème.',
    folderNameLabel: 'Nom du dossier',
    folderNamePlaceholder: 'Ex : Grammaire N3, Kanji du jour',
    cancel: 'Annuler',
    createButton: 'Créer le dossier',
    creatingButton: 'Création...',

    // Dashboard
    cards: 'Cartes',
    dueCount: 'À réviser',
    newCount: 'Nouvelles',
    allPillar: 'Tous',
    vocabPillar: 'Vocabulaire',
    grammarPillar: 'Grammaire',
    kanjiPillar: 'Kanji',
    kanaPillar: 'Kana',
    searchDecksPlaceholder: 'Rechercher paquets et mots...',
    grammarFocusTitle: 'Paquets de grammaire ciblée',
    grammarPointsCount: '{n} points de grammaire',
    studyAllGrammar: 'Étudier la grammaire {level}',
    masteryProgress: 'Progression de maîtrise',
    studyNow: 'Étudier maintenant',
    allCompleted: 'Tout est à jour 🎉',
    newDeckPlaceholder: 'Nom du nouveau paquet...',
    addDeckButton: 'Ajouter paquet',
    addingButton: 'Ajout...',
    noDecksMatch: 'Aucun paquet correspondant',
    noDecksMatchDesc: 'Modifiez vos filtres ou vos termes de recherche.',

    // Study Session
    romajiToggle: 'Romaji',
    sessionCompletedTitle: 'Session terminée !',
    sessionCompletedDesc: 'Bravo ! Toutes les révisions en attente sont terminées pour le moment.',
    again: 'À revoir',
    good: 'Bien',
    easy: 'Facile',
    againSub: 'Again [1]',
    goodSub: 'Good [2]',
    easySub: 'Easy [3]',
    backToDashboard: 'Retour au bureau',
    tapToFlip: 'Tapez ou appuyez sur Espace pour retourner',
    revealAnswer: 'Afficher la réponse [Espace]',
    audioButtonTooltip: 'Écouter la prononciation (Raccourci : R)',
    onyomi: "On'yomi (Lecture sino-japonaise)",
    kunyomi: "Kun'yomi (Lecture japonaise)",
    strokes: 'Traits',
    strokesUnit: 'traits',
    formation: 'Règle de formation',
    exampleSentence: 'Exemple',

    // Manage Deck
    deckSettingsTitle: 'Gestion et édition des cartes',
    bulkImportJson: 'Importation groupée (JSON)',
    closeBulkImport: 'Fermer l’importation JSON',
    bulkImportDesc: 'Collez un tableau JSON ou chargez un fichier .json.',
    selectJsonFile: 'Choisir un fichier (.json)',
    importDataButton: 'Importer les cartes',
    addNewCard: 'Ajouter une nouvelle carte',
    kanjiLabel: 'Kanji / Expression',
    readingLabel: 'Lecture (Hiragana)',
    meaningLabel: 'Sens & Traduction',
    categoryLabel: 'Catégorie',
    jlptLevelSelect: 'Niveau JLPT',
    addCardButton: 'Ajouter la carte',
    registeredCards: 'Cartes enregistrées',
    deleteCard: 'Supprimer',
    repetitionsCount: 'Répétitions',
    intervalCount: 'Intervalle',
    noCardsFound: 'Aucune carte trouvée.',
  },

  de: {
    // Brand & Header
    brandTitle: 'MANABU',
    brandSub: 'Japanisch lernen · JLPT N5–N1 Lernkarten',
    examCountdownPrefix: 'Nächste JLPT-Prüfung in',
    days: 'Tagen',
    hours: 'Std',
    minutes: 'Min',
    reviewDue: 'Wiederholen',
    newFolder: 'Neuer Ordner',
    addFolder: 'Hinzufügen',
    jlptLevelLabel: 'JLPT-Stufe:',
    all: 'Alle',
    kana: 'Kana',
    beginner: 'Anfänger',
    elementary: 'Grundstufe',
    intermediate: 'Mittelstufe',
    upperIntermediate: 'Obere Mittelstufe',
    advanced: 'Fortgeschritten',
    fiftySounds: 'Kana (50)',
    language: 'Sprache',

    // Breadcrumbs & Nav
    collections: 'Sammlungen',
    decks: 'Decks',
    study: 'Lernen',
    stats: 'Statistiken',
    quickReview: 'Fällige wiederholen',
    back: 'Zurück',
    folders: 'Ordner',

    // Collections
    collectionsPortalTitle: 'Japanisch meistern.',
    collectionsPortalSub: 'Spaced Repetition für Vokabeln, Grammatik, Kanji und Kana',
    collectionsPortalDesc: 'Wissenschaftlich gestützt durch die Ebbinghaus-Vergessenskurve mit SRS.',
    totalFolders: 'Ordner gesamt',
    totalDecks: 'Decks gesamt',
    totalCards: 'Karten gesamt',
    collectionsList: 'Sammlungen & Ordner',
    filteringWith: 'Gefiltert nach',
    searchPlaceholder: 'Ordner, Decks, Wörter durchsuchen...',
    viewDecks: 'Decks anzeigen',
    otherDecksCount: '+{n} weitere Decks',
    navDashboard: "Übersicht",
    navExplore: "Beziehungsgraph",
    navLibrary: "Lesebibliothek",
    navProgress: "Fortschritt",
    navSettings: "Einstellungen",
    navDrill: "Fokustraining",
    navExam: "Probeprüfung",
    startReview: "Wiederholung starten",
    studyModes: "Lernmodi",
    levelHubs: "Stufen-Hubs",
    credits: "Danksagung & Lizenzen",
    daysStreak: "{n} Tage Serie",
    home: "Startseite",
    landingHeroHeadline: "Japanisch meistern mit System. Effektive Spaced Repetition.",
    landingHeroSub: "Kanji, Vokabeln, Grammatik und Lesen in einer einzigen SRS-Warteschlange. Angetrieben vom wissenschaftlich erprobten SM-2-Algorithmus.",
    startLearningFree: "Kostenlos starten",
    loginExisting: "Anmelden",
    login: "Anmelden",
    noHiddenFees: "Kostenlos · Keine versteckten Kosten",
    nativeTtsPitch: "Native Aussprache & Tonhöhenakzente",
    mockExamsIncluded: "JLPT-Probeprüfungen inklusive",
    howItWorks: "In 3 Schritten zum Erfolg",
    howItWorksSub: "Kein Pauken: eine tägliche Gewohnheit, berechnet nach der Vergessenskurve.",
    step1Title: "1. Lernen",
    step1Desc: "Strukturierter Einstieg in Strichreihenfolge, Akzente und Grammatikregeln.",
    step2Title: "2. Wiederholen",
    step2Desc: "Die SM-2-Engine berechnet optimale Intervalle kurz vor dem Vergessen.",
    step3Title: "3. Verfolgen",
    step3Desc: "Visualisiere deinen Fortschritt und die Prüfungsbereitschaft über alle 4 Säulen.",
    curriculumByLevel: "Lehrplan nach Stufen",
    curriculumSub: "Vom Grund-Kana bis zum fortgeschrittenen N1, voll strukturierte Datensätze inklusive.",
    unlockAllLevels: "Alle Stufen erkunden →",
    whyChooseManabu: "Warum Manabu",
    graphDifferentiatorTitle: "Beziehungsnetzwerk",
    graphDifferentiatorDesc: "Tippe auf ein Kanji, um Vokabeln zu sehen und tiefer in die Grammatik einzutauchen. Verknüpfe Wissen statt isoliert zu lernen.",
    pitchDifferentiatorTitle: "Tonhöhenverlauf",
    pitchDifferentiatorDesc: "Visualisiere Tonhöhenakzentkonturen für authentische japanische Aussprache.",
    readerDifferentiatorTitle: "Stufenleser & Lesereife",
    readerDifferentiatorDesc: "Lies im Kontext mit unterstrichenen SRS-Wörtern. Tippe auf jedes Wort für Definition und Sofort-Aufnahme ins SRS.",
    unlockDifferentiatorTitle: "Abhängiges Freischalten",
    unlockDifferentiatorDesc: "Grammatik wird erst freigeschaltet, wenn die notwendigen Vokabeln im SRS stabil verankert sind.",
    privacyPolicy: "Datenschutz",
    termsOfService: "Nutzungsbedingungen",
    welcomeBack: "Willkommen zurück",
    streakDays: "{n} Tage Serie",
    streakCompletedToday: "Heute erledigt ✓",
    streakPendingToday: "Heute noch offen",
    srsQueue: "SRS-Warteschlange",
    estMinutes: "Dauer: ca. {n} Min.",
    cardsDueForReview: "Karten fällig",
    allReviewsCompleted: "Alle Wiederholungen für heute abgeschlossen! 🎉",
    examReadiness: "Prüfungsbereitschaft",
    masteryLevel: "{level} Beherrschung",
    readinessDesc: "Berechnet anhand von Karten mit stabilem SRS-Intervall (ab 7 Tagen).",
    viewFluencyProjection: "Detaillierte Prognose ansehen →",
    wordOfTheDay: "Wort des Tages",
    reviewInQueue: "In Warteschlange wiederholen",
    quickDrillTitle: "Fokustraining",
    quickDrillSub: "Fehlerorientiert",
    quickLibraryTitle: "Stufenleser",
    quickLibrarySub: "Lesen mit SRS-Hilfen",
    quickGraphTitle: "Beziehungsgraph",
    quickGraphSub: "Kanji ⇄ Vokabeln ⇄ Grammatik",
    quickExamTitle: "JLPT-Probeprüfung",
    quickExamSub: "Mit Zeitmessung & Audio",
    pause: "Pause (Esc)",
    modeRecognition: "Erkennung",
    modeAudio: "Hörverständnis",
    modeCanvas: "Schreiben",
    pronounce: "Anhören",
    tapToReveal: "Tippen oder Leertaste zum Umdrehen",
    selectRating: "Bewertung wählen",
    keyboardShortcuts: "Tasten: 1, 2, 3, 4",
    whyThisCard: "Warum diese Karte fällig ist (SM-2 Formel)",
    currentInterval: "Aktuelles Intervall",
    easeFactor: "Leichtigkeitsfaktor",
    repetitionCount: "Wiederholungen",
    againBtn: "Nochmal",
    hardBtn: "Schwer",
    goodBtn: "Gut",
    easyBtn: "Einfach",
    sessionFinishedTitle: "Sitzung beendet!",
    sessionFinishedDesc: "Sehr gut! Deine Gedächtnisintervalle wurden in der SRS-Datenbank aktualisiert.",
    reviewedCount: "Karten wiederholt",
    accuracyRate: "Genauigkeit",
    xpEarned: "XP erhalten",
    breakdown: "Aufschlüsselung",
    backToDashboard: "Zurück zur Übersicht",
    reviewAgain: "Nochmal wiederholen",
    drillModeBadge: "Trainingsmodus",
    drillCompletedTitle: "Training beendet!",
    drillCompletedDesc: "Fehlertraining abgeschlossen. Dein langfristiger SM-2-Plan bleibt unberührt.",
    practiceAgain: "Nochmals üben",
    masteredIt: "Gemeistert",
    levelHub: "Stufen-Hub",
    totalRegisteredCards: "{n} Karten gesamt",
    masteryRate: "Beherrschungsrate",
    masterySub: "Feste / Gesamtkarten",
    reviewLevelCards: "{level} wiederholen",
    viewLesson: "Lektion ansehen →",
    startDrillForSet: "Training für diese Einheit starten",
    locked: "Gesperrt",
    backToHub: "Zurück zum Hub",
    commonCompounds: "Häufige Zusammensetzungen",
    formationRule: "Bildungsregel",
    nuanceCallout: "Nuance & Abgrenzung",
    mockExamSetup: "JLPT-Probeprüfung",
    mockExamSub: "Umfassende Probeprüfung nach offiziellen JLPT-Zeit- und Bewertungsvorgaben.",
    timeLimit: "Zeitlimit",
    maxScore: "Höchstpunktzahl",
    passingScore: "Bestehensgrenze",
    sectionalThreshold: "Teilbereich-Mindestwert",
    selectSections: "Abschnitte wählen",
    beginExam: "Prüfung starten →",
    examPassed: "Bestanden (PASSED)",
    examFailed: "Nicht bestanden (NOT PASSED)",
    sectionBreakdown: "Ergebnisse nach Bereichen",
    missedQuestions: "Falsche Fragen",
    addMissedToSrs: "Falsche Fragen zum SRS hinzufügen",
    addedToSrs: "✓ Zum SRS hinzugefügt",
    retakeExam: "Prüfung wiederholen",
    nextQuestion: "Nächste Frage →",
    prevQuestion: "← Vorherige Frage",
    submitExam: "Abgeben & bewerten ✓",
    settingsTitle: "Konto- und Lerneinstellungen",
    profileBasics: "1. Profil-Grunddaten",
    username: "Benutzername",
    targetLevel: "Zielstufe JLPT",
    examDate: "Prüfungsdatum",
    studyEnvironment: "2. Lernumgebung & Anzeige",
    defaultSessionSize: "Standard-Karten pro Sitzung",
    furiganaDefault: "Standard-Furigana",
    dailyReminders: "Tägliche Erinnerungen",
    reducedMotion: "Reduzierte Bewegung",
    saveSettings: "Einstellungen speichern",
    settingsSaved: "✓ Einstellungen gespeichert",
    dangerZone: "3. Datenverwaltung & Gefahrenzone",
    exportData: "Daten exportieren",
    resetProgress: "Zurücksetzen",
    leaderboardTitle: "Wöchentliche Rangliste",
    resetsInDays: "Zurücksetzung in: {n} Tagen",
    leaderboardPrivacy: "Privatsphäre in der Rangliste",
    makePrivate: "Privat machen",
    joinLeaderboard: "Rangliste beitreten",
    rankUser: "Rang / Lerner",
    xpRank: "XP / Rang",
    aboutTitle: "Über Manabu & Lizenzhinweise",
    whyIBuiltThis: "Entstehungshintergrund",
    openDataAttribution: "Open-Data-Quellen & Lizenzen",
    createAccount: "Konto erstellen",
    loginTitle: "Anmelden",
    emailLabel: "E-Mail-Adresse",
    takePlacementQuiz: "Einstufungstest machen?",
    startLearning: "Lernen starten",
    loginAndReview: "Anmelden und wiederholen",
    alreadyHaveAccount: "Bereits ein Konto? Anmelden",
    needAccount: "Neu hier? Registrieren",
    previous: "Zurück",
    next: "Weiter",
    furiganaOn: "Furigana: AN",
    furiganaOff: "Furigana: AUS",
    drillReadyHint: "Starten Sie direkt nach der Lektion ein gezieltes Training",
    meaningTitle: "Bedeutung",
    lessonSetLabel: "Lektionen-Set ({count} Einträge)",
    otherDecksCount: "und {count} weitere Decks...",
    noDecksInFolder: 'Keine passenden Decks',
    noCollectionsFound: 'Keine Sammlungen gefunden',
    noCollectionsDesc: 'Keine Treffer für die gewählten Filter.',
    resetFilter: 'Filter zurücksetzen',
    createFolderModalTitle: 'Neue Sammlung erstellen',
    createFolderModalDesc: 'Organisieren Sie Ihr Lernmaterial nach JLPT-Stufe oder Thema.',
    folderNameLabel: 'Ordnername',
    folderNamePlaceholder: 'z.B. N3 Grammatik, Tägliche Kanji',
    cancel: 'Abbrechen',
    createButton: 'Ordner erstellen',
    creatingButton: 'Erstelle...',

    // Dashboard
    cards: 'Karten',
    dueCount: 'Fällig',
    newCount: 'Neu (Ungelernt)',
    allPillar: 'Alle',
    vocabPillar: 'Vokabeln',
    grammarPillar: 'Grammatik',
    kanjiPillar: 'Kanji',
    kanaPillar: 'Kana',
    searchDecksPlaceholder: 'Decks und Wörter suchen...',
    grammarFocusTitle: 'Grammatik-Decks',
    grammarPointsCount: '{n} Grammatikpunkte',
    studyAllGrammar: 'Alle {level} Grammatik lernen',
    masteryProgress: 'Lernfortschritt',
    studyNow: 'Jetzt lernen',
    allCompleted: 'Alles erledigt 🎉',
    newDeckPlaceholder: 'Neuer Deckname...',
    addDeckButton: 'Deck hinzufügen',
    addingButton: 'Hinzufügen...',
    noDecksMatch: 'Keine Decks gefunden',
    noDecksMatchDesc: 'Passen Sie Suchbegriff oder Stufe an.',

    // Study Session
    romajiToggle: 'Romaji',
    sessionCompletedTitle: 'Lerneinheit beendet!',
    sessionCompletedDesc: 'Gute Arbeit! Alle fälligen Karten wurden für heute wiederholt.',
    again: 'Nochmal',
    good: 'Gut',
    easy: 'Einfach',
    againSub: 'Again [1]',
    goodSub: 'Good [2]',
    easySub: 'Easy [3]',
    backToDashboard: 'Zurück zur Übersicht',
    tapToFlip: 'Tippen oder Leertaste zum Umdrehen',
    revealAnswer: 'Antwort aufdecken [Leertaste]',
    audioButtonTooltip: 'Aussprache anhören (Taste: R)',
    onyomi: "On'yomi (Chinesische Lesung)",
    kunyomi: "Kun'yomi (Japanische Lesung)",
    strokes: 'Striche',
    strokesUnit: 'Striche',
    formation: 'Bildungsregel',
    exampleSentence: 'Beispiel',

    // Manage Deck
    deckSettingsTitle: 'Deck-Einstellungen & Karten bearbeiten',
    bulkImportJson: 'Massenimport (JSON)',
    closeBulkImport: 'JSON-Import schließen',
    bulkImportDesc: 'Fügen Sie ein JSON-Array ein oder laden Sie eine .json-Datei hoch.',
    selectJsonFile: 'Datei auswählen (.json)',
    importDataButton: 'Karten importieren',
    addNewCard: 'Neue Karte hinzufügen',
    kanjiLabel: 'Kanji / Ausdruck',
    readingLabel: 'Lesung (Hiragana)',
    meaningLabel: 'Bedeutung & Übersetzung',
    categoryLabel: 'Kategorie',
    jlptLevelSelect: 'JLPT-Stufe',
    addCardButton: 'Karte hinzufügen',
    registeredCards: 'Registrierte Karten',
    deleteCard: 'Löschen',
    repetitionsCount: 'Wiederholungen',
    intervalCount: 'Intervall',
    noCardsFound: 'Keine Karten gefunden.',
  },
};

const LanguageContext = createContext({
  language: 'en',
  setLanguage: (lang) => {},
  t: (key, params) => key,
  languages: LANGUAGES,
});

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState('en');
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    try {
      const savedLang = localStorage.getItem('anki-lang');
      if (savedLang && TRANSLATIONS[savedLang]) {
        setLanguageState(savedLang);
      } else {
        // Detect browser language if available
        const navLang = navigator.language?.slice(0, 2);
        if (navLang && TRANSLATIONS[navLang]) {
          setLanguageState(navLang);
        }
      }
    } catch (e) {
      console.error(e);
    }
    setMounted(true);
  }, []);

  const setLanguage = (lang) => {
    if (TRANSLATIONS[lang]) {
      setLanguageState(lang);
      try {
        localStorage.setItem('anki-lang', lang);
      } catch (e) {
        console.error(e);
      }
    }
  };

  const t = (key, params = {}) => {
    const dict = TRANSLATIONS[language] || TRANSLATIONS.en;
    let text = dict[key] || TRANSLATIONS.en[key] || key;

    // Substitute params like {n} or {level}
    if (typeof text === 'string') {
      Object.entries(params).forEach(([paramKey, paramVal]) => {
        text = text.replace(new RegExp(`\\{${paramKey}\\}`, 'g'), String(paramVal));
      });
    }

    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languages: LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}

